### ISSUE TITLE
slice out of range error at func `ReportLoad`

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#102]
### Describe the bug（Bug 描述）

Panic appears in the `ReportLoad` function of logs in a stable environment.

https://github.com/openGemini/openGemini/blob/346243cdfc7c76223589fa31b762b453021b344a/app/ts-store/storage/storage.go#L254

It seems that there is a problem with log printing

### Expected behavior（期望结果）

Panic should not appear in log printing

**Comment by lyric315** [comment]
I’ll fix this

**Comment by xiangyu5632** [comment]
> I’ll fix this
thx @lyric315
