### ISSUE TITLE
openGemini的源码编译指导问题请教

### ISSUE THREAD

**Issue by bwu215** [openGemini/openGemini#111]
### Describe your question

你好：
	我这边在根据开源[openGemini/README_CN.md at main · openGemini/openGemini · GitHub](https://github.com/openGemini/openGemini/blob/main/README_CN.md)进行自编码时，出现如下问题，请问该如何处理。
我这边的操作如下：
1）	配置设置了本地环境的代理
git config --global http.proxy http://proxyUsername:proxyPassword@proxyhk.xxx.com:8080/
git config --global https.proxy http://proxyUsername:proxyPassword@proxyhk.xxx.com:8080/
2）	从[Downloads - The Go Programming Language (google.cn)](https://golang.google.cn/dl/) 中安装了go1.19.5.linux-amd64.tar.gz 依赖包。
3）	环境部署了python 3.4.6 
4）	参考编译指导完成了源码下载，环境参数设置，执行python3 build.py出现如下报错：
[INFO] check_environ: Checking environment...
[INFO] check_prereqs: Checking for dependencies...
[INFO] build: Starting build for linux/amd64...
[INFO] build: Using Go version: 1.19.5
[INFO] build: Using git branch: main
[INFO] build: Using git commit: c8115547a74186c62e9858a598f8bfcfb8ccc062
[INFO] build: Sending build output to: /data1/test/openGemini/src/openGemini/build
[INFO] build: Using version '0.2.0' for build.
[INFO] build: Building target: ts-sql
[INFO] build: GOOS=linux GOARCH=amd64 go build -mod=mod -o /data1/test/openGemini/src/openGemini/build/ts-sql -ldflags="-X main.TsVersion=0.2.0 -X main.TsBranch=main -X main.TsCommit=c8115547a74186c62e9858a598f8bfcfb8ccc062" ./app/ts-sql
[ERROR] run: Command 'GOOS=linux GOARCH=amd64 go build -mod=mod -o /data1/test/openGemini/src/openGemini/build/ts-sql -ldflags="-X main.TsVersion=0.2.0 -X main.TsBranch=main -X main.TsCommit=c8115547a74186c62e9858a598f8bfcfb8ccc062" ./app/ts-sql' failed with error: b'go: github.com/BurntSushi/toml@v0.4.1: Get "https://goproxy.cn/github.com/%21burnt%21sushi/toml/@v/v0.4.1.mod": dial tcp 175.6.206.41:443: i/o timeout\ngo: downloading github.com/VictoriaMetrics/VictoriaMetrics v1.67.0\ngo: downloading go.uber.org/zap v1.19.1\ngo: downloading github.com/spf13/cobra v1.3.0\ngo: downloading github.com/influxdata/influxdb v1.9.5\ngo: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.1-0.20190411184413-94d9e492cc53\ngo: downloading github.com/influxdata/influxql v1.1.1-0.20210223160523-b6ab99450c93\ngo: downloading golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4\ngo: downloading google.golang.org/protobuf v1.27.1\ngo: downloading github.com/BurntSushi/toml v0.4.1\ngo: downloading golang.org/x/text v0.3.7\ngo: downloading github.com/hashicorp/raft v1.3.1\ngo: downloading github.com/pingcap/failpoint v0.0.0-20200702092429-9f69995143ce\ngo: downloading github.com/gogo/protobuf v1.3.2\ngo: downloading github.com/golang/snappy v0.0.4\ngo: downloading github.com/pkg/errors v0.9.1\ngo: downloading github.com/tinylib/msgp v1.1.2\ngo: downloading github.com/valyala/fastjson v1.6.3\ngo: downloading github.com/golang-jwt/jwt v3.2.1+incompatible\ngo: downloading github.com/json-iterator/go v1.1.12\ngo: downloading github.com/apache/arrow/go/arrow v0.0.0-20200923215132-ac86123a3f01\ngo: downloading github.com/xlab/treeprint v1.1.0\ngo: downloading github.com/prometheus/common v0.32.1\ngo: downloading golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac\ngo: downloading github.com/prometheus/client_golang v1.12.1\ngo: downloading github.com/armon/go-metrics v0.3.10\ngo: downloading github.com/hashicorp/memberlist v0.3.1\ngo: downloading github.com/prometheus/prometheus v1.8.2-0.20201119142752-3ad25a6dc3d9\ngo: downloading github.com/VictoriaMetrics/fastcache v1.7.0\ngo: downloading github.com/RoaringBitmap/roaring v0.9.1\ngo: downloading github.com/cockroachdb/pebble v0.0.0-20211013210608-e95e73745ce8\ngo: downloading github.com/mitchellh/copystructure v1.2.0\ngo: github.com/BurntSushi/toml@v0.4.1: Get "https://goproxy.cn/github.com/%21burnt%21sushi/toml/@v/v0.4.1.mod": dial tcp 175.6.206.41:443: i/o timeout\n'
[INFO] write_to_gobuild: write to file
Traceback (most recent call last):
  File "build.py", line 143, in run
    out = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=shell)
  File "/usr/lib64/python3.4/subprocess.py", line 617, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'GOOS=linux GOARCH=amd64 go build -mod=mod -o /data1/test/openGemini/src/openGemini/build/ts-sql -ldflags="-X main.TsVersion=0.2.0 -X main.TsBranch=main -X main.TsCommit=c8115547a74186c62e9858a598f8bfcfb8ccc062" ./app/ts-sql' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 574, in <module>
    sys.exit(main(args))
  File "build.py", line 466, in main
    static=args.static):
  File "build.py", line 374, in build
    run(build_command, shell=True)
  File "build.py", line 153, in run
    write_to_gobuild(e.output)
  File "build.py", line 382, in write_to_gobuild
    f.write("error\n")
TypeError: 'str' does not support the buffer interface
5） 单独调用
GOOS=linux GOARCH=amd64 go build -mod=mod -o /data1/test/openGemini/src/openGemini/build/ts-sql -ldflags="-X main.TsVersion=0.2.0 -X main.TsBranch=main -X main.TsCommit=c8115547a74186c62e9858a598f8bfcfb8ccc062" ./app/ts-sql
报错如下：
go: github.com/BurntSushi/toml@v0.4.1: Get "https://goproxy.cn/github.com/%21burnt%21sushi/toml/@v/v0.4.1.mod": dial tcp 175.6.206.41:443: i/o timeout
go: downloading github.com/influxdata/influxdb v1.9.5
go: downloading github.com/VictoriaMetrics/VictoriaMetrics v1.67.0
go: downloading go.uber.org/zap v1.19.1
go: downloading github.com/spf13/cobra v1.3.0
go: downloading github.com/BurntSushi/toml v0.4.1
go: downloading github.com/pingcap/failpoint v0.0.0-20200702092429-9f69995143ce
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/hashicorp/raft v1.3.1
go: downloading golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4
go: downloading github.com/influxdata/influxql v1.1.1-0.20210223160523-b6ab99450c93
go: downloading github.com/apache/arrow/go/arrow v0.0.0-20200923215132-ac86123a3f01
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.1-0.20190411184413-94d9e492cc53
go: downloading google.golang.org/protobuf v1.27.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/tinylib/msgp v1.1.2
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/armon/go-metrics v0.3.10
go: downloading github.com/hashicorp/memberlist v0.3.1
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/prometheus/client_golang v1.12.1
go: downloading github.com/prometheus/common v0.32.1
go: downloading github.com/prometheus/prometheus v1.8.2-0.20201119142752-3ad25a6dc3d9
go: downloading golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac
go: downloading github.com/golang-jwt/jwt v3.2.1+incompatible
go: downloading github.com/mitchellh/copystructure v1.2.0
go: downloading github.com/valyala/fastjson v1.6.3
go: downloading github.com/VictoriaMetrics/fastcache v1.7.0
go: downloading github.com/RoaringBitmap/roaring v0.9.1
go: downloading github.com/cockroachdb/pebble v0.0.0-20211013210608-e95e73745ce8
go: github.com/BurntSushi/toml@v0.4.1: Get "https://goproxy.cn/github.com/%21burnt%21sushi/toml/@v/v0.4.1.mod": dial tcp 175.6.206.41:443: i/o timeout	

问题： dial tcp 175.6.206.41:443: i/o timeout的报错原因是什么？ 同时该如何解决该问题？

**Comment by xiangyu5632** [comment]
是的，在内网是不能编译通过，需要修改一些地方，由于问题不具备普遍性，您可以welink搜索向宇，云数据库创新Lab的是我，我给您进行内网编译指导。

**Comment by zedware** [comment]
I guess the problem is caused by the proxy or enterprise certificates.  Please ask for help from your IT administration team.
