### ISSUE TITLE
The query with limit does not return the lowest tag points

### ISSUE THREAD

**Issue by lihanxue** [openGemini/openGemini#130]
### Describe the bug（Bug 描述）

The query with limit does not return the lowest tag points

### To Reproduce（Bug 复现步骤）

1.insert such datas:
![图片1](https://user-images.githubusercontent.com/31127693/220339823-21cbfdbd-5c0c-4611-9160-6e47fb8a17ce.png)
2.query "select * from mst1 limit 1"
3.result point is not the lowest.
![图片2](https://user-images.githubusercontent.com/31127693/220340428-a3e89e34-bbd1-4a8b-b3c8-53e46ccfd28f.png)

### Expected behavior（期望结果）

The query with limit should return the sorted tag points of the equal minimum time points.

**Comment by zedware** [comment]
In standard SQL, a SELECT statement without ORDER BY may return the rows in any order.
Did openGemini design and document that the rows are ordered by the timestamp in ascending order,
even when there is no "ORDER BY ts" clause?

**Comment by lihanxue** [comment]
> In standard SQL, a SELECT statement without ORDER BY may return the rows in any order. Did openGemini design and document that the rows are ordered by the timestamp in ascending order, even when there is no "ORDER BY ts" clause?
Yes, queries without “ORDER BY” clause in openGemini return data sorted in ascending time by default.
