### ISSUE TITLE
SELECT statement executes for more than 30s when meausurement does not exist

### ISSUE THREAD

**Issue by lijieac** [openGemini/openGemini#131]
### Describe the bug（Bug 描述）

The select statement executes for more than 30s when measurement does not exist.

### Expected behavior（期望结果）

When the measurement does not exist, the select statement execution immediately returns a relative failure error.

**Comment by zedware** [comment]
Thanks for the bug report. Please mention the openGemini version number and the SELECT statement. e.g.

> show measurements
name: measurements
name
----
sensor

> select * from not_exists
<reported an error after 30s or just stopped here without outputing anything?>
