### ISSUE TITLE
openGemini缺少数据订阅功能

### ISSUE THREAD

**Issue by dxzxomy** [openGemini/openGemini#136]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

openGemini缺少数据订阅功能

**Comment by iiiuwioajdks** [comment]
I have done an internship related to stream subscription in a time series database before. If possible, I would like to try this task @xiangyu5632

**Comment by shilinlee** [comment]
> I have done an internship related to stream subscription in a time series database before. If possible, I would like to try this task @xiangyu5632

Can you reach me by Wechat: `shilinlee_com`?

@iiiuwioajdks
