### ISSUE TITLE
ts-server does not support remote connections

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#170]
# Welcome to claim this task
difficulty：⭐

### Describe the bug（Bug 描述）

ts-server does not support remote connections.

When I use [docker](https://hub.docker.com/r/opengeminidb/opengemini-server) to deploy `ts-server`, I can't use `ts-cli` outside the container to connect `ts-server`

**I'm guessing because ts-server doesn't support starting on `0.0.0.0`**

### To Reproduce（Bug 复现步骤）

1. docker run -d -p 8086:8086 --name opengemini-server-example opengeminidb/opengemini-server
2. ts-cli
3. ts-cli -host 0.0.0.0 -port 8086
4. ts-cli -host 127.0.0.1 -port 8086
5. ts-cli -host localhost -port 8086

### Expected behavior（期望结果）

1. `openGemini-server` running in the container.
2. `ts-cli` can connect to the `openGemini-server` from outside the container

**Comment by xiangyu5632** [comment]
Anybody fix it?
