### ISSUE TITLE
ts-cli support import data

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#186]
# Welcome to claim this task

difficulty：⭐⭐⭐

### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

The openGemini does not support import data offline now.

### Describe the solution you'd like（问题的解决办法是什么）

support import file data by ts-cli:

```shell
curl -G  https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt > NOAA_data.txt

./ts-cli -import -path=NOAA_data.txt -host=127.0.0.1 -port=8086
```

**Comment by xmh1011** [comment]
I fix it.
