### ISSUE TITLE
安装启动失败

### ISSUE THREAD

**Issue by whenyd** [openGemini/openGemini#190]
### Describe the bug（Bug 描述）

1. 先用了Release里面的二进制启动, 提示
    `Get "http://127.0.0.1:8086/ping": dial tcp 127.0.0.1:8086: connect: connection refused`
2. 然后尝试下载源码编译, 直接下载zip包编译报错, 提示
    `subprocess.CalledProcessError: Command '['git', 'rev-parse', '--abbrev-ref', 'HEAD']' returned non-zero exit status 128.`
似乎因为不是git仓库, 然后clone了一个, 进去还是报错
    `subprocess.CalledProcessError: Command 'GOOS=linux GOARCH=amd64 go build -mod=mod -o openGemini/build/ts-cli -ldflags="-X main.TsVersion=1.0.1 -X main.TsBranch=main -X main.TsCommit=d32e6643606290e07aa2becbf6f2eea34e7ae950" ./app/ts-cli' returned non-zero exit status 1.`
同时还有个错
`TypeError: write() argument must be str, not bytes`
这个错用zip包编译也有. 
二进制的使用方式也没有个文档.

**Comment by whenyd** [comment]
编译报错有个内容是
`[ERROR] run: Command 'GOOS=linux GOARCH=amd64 go build -mod=mod -o openGemini/build/ts-cli -ldflags="-X main.TsVersion=1.0.1 -X main.TsBranch=main -X main.TsCommit=d32e6643606290e07aa2becbf6f2eea34e7ae950" ./app/ts-cli' failed with error: b"verifying github.com/pkg/sftp@v1.10.1/go.mod: checksum mismatch\n\tdownloaded: h1:lghtmG9kQXohSRq42zV3Nyxyc3+Ox2tv5IIb7Y7IluI=\n\tgo.sum:     h1:lYOWFsE0bwd1+KfKJaKeuokY15vzFx25BLbzYYoAxZI=\n\nSECURITY ERROR\nThis download does NOT match an earlier download recorded in go.sum.\nThe bits may have been replaced on the origin server, or an attacker may\nhave intercepted the download attempt.\n\nFor more information, see 'go help module-auth'.\n"`

**Comment by xiangyu5632** [comment]
谢谢反馈，我来回答您的问题
1. 中文文档会尽快在4月底前正式上线官网，您现在遇到部署的问题，给您的解答如下：
