### ISSUE TITLE
ts-cli support changing chunk size for query

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#193]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

```shell
> python3 build.py --clean
```

then execute:

![image](https://user-images.githubusercontent.com/22270117/231967465-fc80a4a4-79be-460c-9756-e27614b0e7d9.png)

### Describe the solution you'd like（问题的解决办法是什么）

support like this:

![image](https://user-images.githubusercontent.com/22270117/231967692-eb94f9f5-2540-424f-8fd2-c6cd2517b7bc.png)

**Comment by SuFIND** [comment]
I will fix it.
