### ISSUE TITLE
I mistakenly wrote data with `time` as tag key

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#200]
### Describe the bug（Bug 描述）

I mistakenly wrote data with `time` as tag key.

### To Reproduce（Bug 复现步骤）

1. start openGemini server or cluster.
2. use ts-cli to connect service.

```sql
> create database db0
> use db0
Using database db0
> insert mst,tag=1,time=12 f1=2
> select * from mst
name: mst
time                f1 tag time
----                -- --- ----
1681714227781522000 2  1   12
```

### Expected behavior（期望结果）

Writing to the tag key `time` should be disabled.

**Comment by ztygreat** [comment]
I will fix it.

**Comment by xmh1011** [comment]
I fix it.
