### ISSUE TITLE
please fix the static analysis warnings

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#214]
### Describe your question

![image](https://user-images.githubusercontent.com/22270117/232835770-39ca00f9-49a7-406b-bf3b-4ccda0f6905e.png)
![image](https://user-images.githubusercontent.com/22270117/232836002-185abc10-8b31-4591-9d96-67a3ae8ff415.png)

**Comment by xmh1011** [comment]
I fix it
