### ISSUE TITLE
using an open source version directly for pbkdf2

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#232]
### Describe your question

Directly use the open source version `golang.org/x/crypto/pbkdf2 v0.5.0` at `go.mod`,
delete `open_src/golang.org/x/crypto/pbkdf2`.

remove the dir:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/22270117/233817531-ac4e47b0-75cc-4180-97cd-15f5f69de704.png">

**Please verify whether the function is compatible after modification.**

### ref

https://github.com/golang/crypto/blob/master/pbkdf2/pbkdf2.go

**Comment by 1156230954** [comment]
I will fix it
