### ISSUE TITLE
using an open source version directly for golang-set

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#233]
### Describe your question

Directly use the open source version `github.com/deckarep/golang-set v1.8.0` at `go.mod`,
remove `open_src/github.com/deckarep/golang-set`.

**Please verify whether the function is compatible after modification.**

### ref
https://github.com/deckarep/golang-set/blob/v1.8.0/go.mod

**Comment by 1156230954** [comment]
I will fix it
