### ISSUE TITLE
A CLI tool should be provided by openGemini.

### ISSUE THREAD

**Issue by zhouruiapple** [openGemini/openGemini#24]
If we want to develop or maintenance openGemini, we must download and compile a binary of CLI tool from influxdb which version is lower than 2.0. This is very inconvenient and we need to maintain an additional copy of the code of influxdb. Another alternative is to install influxdb CLI tool from system software repository. But some system software repository many not have the CLI tool of influxdb or the correct version CLI tool of influxdb. It is too bad.

A build-in CLI tool for openGemini should be provided by openGemini. It explore data from openGemini by SQL-Like query language(GeminiQL). Pls see below example:
```
> SELECT * FROM "mst0"

name: mst0
--------------
time                   t1    t2    v1     v2
2022-10-09T21:34:00Z   a     b     10     20
2022-10-09T21:34:01Z   a     b     10     20
[...]
2022-10-09T21:40:01Z   a     b     10     20
2022-10-09T21:40:02Z   a     b     10     20
```

The above example queries all time series from mst0 and echos the result set back to the terminal. The features of the first version of CLI tool of openGemini have to be compatible with influxdb CLI.

**Comment by xiangyu5632** [comment]
openGemini really should have its own CLI.  someone can help make it happen

**Comment by xiangyu5632** [comment]
thx @zhouruiapple
