### ISSUE TITLE
ts-cli write field_value with blank space failed

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#243]
### Describe the bug（Bug 描述）

ts-cli write field_value with blank space failed.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/22270117/234167017-5a371389-cdce-4d44-baf0-520fef7df199.png">

second:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/22270117/234168974-7a0b6143-834e-4e88-96f6-0a5fb8f61816.png">

### To Reproduce（Bug 复现步骤）

1. start ts-server.
2. ./build/ts-cli
3. create database db0
4. use db0
5. insert weather,location=us-midwest temperature="too warm"
    
   **ERR: error parsing query: syntax error: unexpected IDENT**

6. insert weather,location=us-midwest temperature="toowarm"
7. select * from weather
```
name: weather
+---------------------+------------+-------------+
| time                | location   | temperature |
+---------------------+------------+-------------+
| 1682393021308851000 | us-midwest | toowarm     |
+---------------------+------------+-------------+
3 columns, 1 rows in set
```

### Expected behavior（期望结果）

`insert weather,location=us-midwest temperature="too warm"`

can write to ts-server successfully.

**Comment by Benevor** [comment]
I will fix it.
