### ISSUE TITLE
kubeEdge should be provided by openGemini

### ISSUE THREAD

**Issue by xiangyu5632** [openGemini/openGemini#25]
In the Internet of Things, the Industrial Internet of Things, and the Internet of Vehicles, edge computing is more and more widely used. To ensure data security, reduce network bandwidth, and improve the time validity of data processing, data needs to be stored, calculated, decided, and applied at the edge side.
In edge computing, KubeEdge supports access to multiple devices and can still work properly in complex network environments, which has become a de facto standard.
Currently, OpenGemini does not support KubeEdge. Therefore, OpenGemini cannot be used in application scenarios such as IoT and industrial IoT.
To implement this function, need to:
1. Create a docker file to support container deployment.
2. Implement KubeEdge Mappers Adapter and write data to openGemini.
3. Cloud-edge data synchronization can be implemented based on KubeEdge.
![yunbian](https://user-images.githubusercontent.com/49023462/194793881-c808bace-7c84-4d38-983d-121a64e0b15e.PNG)

**Comment by wesley-fly** [comment]
iot场景arm架构居多，openGemini目前支持arm吗？

**Comment by xiangyu5632** [comment]
> 
openGemini目前还不能支持arm，需要一点时间做代码迁移（适配），争取在0.2的版本中得到支持。
