### ISSUE TITLE
support CQ syntax for GeminiQL

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#257]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

In order to support the CQ function, it is first necessary to support syntax analysis.

### Describe the solution you'd like（问题的解决办法是什么）

support GeminiQL like:

reference: https://docs.influxdata.com/influxdb/v1.8/query_language/continuous_queries/

1. create 

```sql
CREATE CONTINUOUS QUERY <cq_name> ON <database_name>
RESAMPLE EVERY <interval> FOR <interval>
BEGIN
  <cq_query>
END
```

<cq_query>:

```sql
SELECT <function[s]> INTO <destination_measurement> FROM <measurement> [WHERE <stuff>] GROUP BY time(<interval>)[,<tag_key[s]>]
```

<destination_measurement>: 

```sql
<db>.<rp>.<mst>
```

2. show

```sql
SHOW CONTINUOUS QUERIES
```

3. drop

```sql
DROP CONTINUOUS QUERY <cq_name> ON <database_name>
```

**Comment by Benevor** [comment]
I will try to support it.
