### ISSUE TITLE
add query protection feature

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#274]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

Throws an error if the query has no time condition.

### Describe the solution you'd like（问题的解决办法是什么）

1. Configuration items need to be added, and this protection feature is turned off by default
2. Throws an error if the query has no time condition.

**Comment by big-dust** [comment]
I will support it.
