### ISSUE TITLE
refactoring of ts-cli's command line parameters using cobra

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#297]
### Describe your question

to support nested subcommands help

```bash
ts-cli
ts-cli import ...
ts-cli export ...
ts-cli execute ...
ts-cli version
```

Only display the help information for the corresponding subcommand.

ref: https://cobra.dev/

**Comment by achintya-7** [comment]
I will support it

**Comment by xmh1011** [comment]
I will support it.
