### ISSUE TITLE
github action supports incremental coverage by codecov

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#298]
### Describe your question

Now:

<img width="857" alt="image" src="https://github.com/openGemini/openGemini/assets/22270117/d59c7fe6-fb0b-4828-8e89-eb941485cdc2">

Expected:

<img width="830" alt="image" src="https://github.com/openGemini/openGemini/assets/22270117/0f48c8b3-9268-445a-9595-b1026416e55f">

**Comment by big-dust** [comment]
I will support it.
