### ISSUE TITLE
Support FULL JOIN operation

### ISSUE THREAD

**Issue by lihanxue** [openGemini/openGemini#32]
In some scenarios, in order to analyze time series data more flexibly, we need to use FULL JOIN operation. For example, we have such a source measurement:
```
> SELECT * FROM m
name: m
time                host region total val
----                ---- ------ ----- ---
1434055562000000000 1    east   2     3
1434055562000000000 1    west   2     1
1434055562000000000 2    east   2     4
1434055562000000000 2    west   2     2
```
Users can write the following query statement to use FULL JOIN and get the following results:
```
> SELECT m1.val, m2.val FROM (SELECT val FROM m WHERE host = '1') AS m1 FULL JOIN (SELECT val FROM m WHERE host = '2') AS m2 ON (m1.region = m2.region AND m1.total = m2.total) GROUP BY region, total 
name: m1,m2
tags: region=east, total=2
time                m1.val m2.val
----                ------ ------
1434055562000000000 3      4

name: m1,m2
tags: region=west, total=2
time                m1.val m2.val
----                ------ ------
1434055562000000000 1      2
```
The FULL JOIN query statement joins the left and right subqueries with the equivalent condition after the keyword ON as the join condition, and can use the sort join algorithm based on the sort key after GROUP BY.

**Comment by xiangyu5632** [comment]
this function has been supported， It will support v1.0
