### ISSUE TITLE
support to new subscription service and make sense

### ISSUE THREAD

**Issue by shilinlee** [openGemini/openGemini#328]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

- New subscription service
- Make it work

### Describe the solution you'd like（问题的解决办法是什么）

- add one new subscription service
- design appropriate configuration items
- guaranteed a certain degree of reliability

**Comment by ZelinMa557** [comment]
/ I will support it
