### ISSUE TITLE
README_CN compile scripts error

### ISSUE THREAD

**Issue by zealzhangz** [openGemini/openGemini#361]
### Describe your question

README_CN compile scripts `python build.py -clean`  clean param error

**Comment by shilinlee** [comment]
try `python build.py --clean`

**Comment by shilinlee** [comment]
> ### Describe your question
> README_CN compile scripts `python build.py -clean` clean param error

Sorry for that typo.

See https://docs.opengemini.org/zh/guide/quick_start/get_started.html
