### ISSUE TITLE
openGemini 1.0.0不支持创建带有":"冒号的measurement名

### ISSUE THREAD

**Issue by dxzxomy** [openGemini/openGemini#377]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

openGemini 1.0.0不支持创建带有":"冒号的measurement名.

>>> create measurement node_exporter:cpu:count
Elapsed: 687.294µs
ERR: error parsing query: syntax error: unexpected $un

**Comment by ZelinMa557** [comment]
很少有数据库会支持表名带特殊字符吧，这个改动会牵扯词法分析和语法分析器

**Comment by shilinlee** [comment]
> 很少有数据库会支持表名带特殊字符吧，这个改动会牵扯词法分析和语法分析器

`:` 其实是可以支持的，不涉及语法解析，是内部逻辑判断有硬编码。

**Comment by wtsclwq** [comment]
I will try it.
