### ISSUE TITLE
Index tag Order selection

### ISSUE THREAD

**Issue by lihanxue** [openGemini/openGemini#383]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

In the case of multi-tag-AND query, for example, SELECT * FROM mst WHERE tag1=1 AND tag2=2, the current implementation of OpenGemini is indexing all tags, and then computing the intersection of SIDs indexed by each tag. This is not friendly to tags with small cardinality which's index results may include almost all SIDs. Therefore, whether OpenGemini can index the tag with a large cardinality first and then perform pruning on the subsequent tags based on the first index result. Or more generally, whether OpenGemini can provide a scheme for index order selection of multi-tag-AND query.

### Describe the solution you'd like（问题的解决办法是什么）

Currently, OpenGemini does not have cardinality statistics thus can refer to the VictoriaMetrics design.
1. All tags are sorted by Loopcount. The first tag that is filtered by the same value is used to index its SID,
2. The remaining tags are sorted by Filterloopscount. After the sorting, the remaining tags are traversed, the SIDs of the tags are indexed, and the intersection of the SIDs is obtained to update the SIDs result. If the Filterloopscount of a tag is greater than the count of SIDs in the current SIDs result multiplied by the Default Loopcount threshold of each SID, subsequent tags starting from this tag are not indexed but filtered in step 3.
3. Filter the remaining tags that do not have indexes in step 2.

Loopcount refers to the number of SIDs indexed by the tag in Step 1, and Filterloopscount refers to the number of SIDs indexed by the tag in Step 2. The basic principle is to collect statistics on the number of SIDs of the previous query index, which is used as the basis for the estimation of the current query. The algorithm starts from the tag with the smallest number of SIDs. In addition, a threshold is set to prevent the tag with a large number of SIDs from being indexed which is to be directly filtered. More detail see [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/index_db.go).

**Comment by ZelinMa557** [comment]
I will support it

**Comment by ZelinMa557** [comment]
I have read the above description and understood the basic idea, but I have a small question, what does the loopcount & filterloopscount mean? Is there any examples?

**Comment by ZelinMa557** [comment]
I have made a basic version. Since the changes involve critical paths, a more rigorous code review may be required in the future. The pr link is https://github.com/openGemini/openGemini/pull/404. Do you have time to take a look? @lihanxue @shilinlee
