### ISSUE TITLE
使用高基数引擎创建measurement，在设置数据类型为tag时出现错误。

### ISSUE THREAD

**Issue by HEEE61** [openGemini/openGemini#406]
### Describe the bug（Bug 描述）

按照使用文档中的信息创建measurement，语句如下：
CREATE MEASUREMENT mst (location string tag default "", direction string tag default "", rtt int field default 0,) WITH ENGINETYPE = columnstore SHARDKEY location TYPE hash PRIMARYKEY location, direction SORTKEY time
创建完成后，插入一条数据，语句如下：
INSERT mst2 location="a",direction="b",rtt=10i
发生错误如下：
ERR: Post "http://localhost:8086/write?consistency=&db=testDB&precision=ns&rp=": EOF
PS：
伪集群中的sql进程直接结束

### Screenshots（屏幕截图）

当创建表时设置字段的数据类型为tag时如下：
![error-tag](https://github.com/HEEE61/Pictures/blob/main/WriteUse/error-tag.png?raw=true)
当创建表时设置字段的数据类型全为field时，操作成功如下：
![error-tag](https://github.com/HEEE61/Pictures/blob/main/WriteUse/success.png?raw=true)

**Comment by xiangyu5632** [comment]
最新的v1.1.0版本吗？最新版本上，使用高基数引擎创建表的语法有所变化，如果是使用的新版本，稍等一下，新的文档就快更新了。

**Comment by HEEE61** [comment]
好的，谢谢
