### ISSUE TITLE
One time range corresponds to multiple indexes

### ISSUE THREAD

**Issue by zhenyuxie** [openGemini/openGemini#41]
**Describe the bug** 
The index group  in openGemini like shard group, it is responsible for dividing the index data into corresponding time range. So,  an index group only corresponds to a time range，that's to say a time range only corresponds to a index. But actually I found multiple indexes on the same time range. This bug causes index bloat, wasting performance and storage.
**To Reproduce**
1. just start the ts-server
2. set shard duration to 1d
3. set index duration to 1d
4. insert into a point in today then insert into a point in tomorrow and a point in the day after tomorrow
5. insert into a point in today, then you'll see tow index directories which time range is today.

**Expected behavior**
One time range only corresponds to  one index.

**Comment by zhouruiapple** [comment]
@zhenyuxie can you give us a directories output about the index?

**Comment by zhenyuxie** [comment]
> @zhenyuxie can you give us a directories output about the index?

Yeap, sure.

**Comment by zhenyuxie** [comment]
> @zhenyuxie can you give us a directories output about the index?

This is my use case:
![image](https://user-images.githubusercontent.com/15904723/195485093-a015f43a-7d9f-4eb0-808b-0382f952c807.png)
And this is result about index directories:
![image](https://user-images.githubusercontent.com/15904723/195485257-ee07ddb4-2e99-4802-ac5b-89a3d60c20ec.png)
We can see index 2 and index 5 have same time range.

**Comment by zhouruiapple** [comment]
This is terrible. We should fix it as soon as possible. @zhenyuxie Can you fix it?

**Comment by zhenyuxie** [comment]
> This is terrible. We should fix it as soon as possible. @zhenyuxie Can you fix it?

Yes, see this pr https://github.com/openGemini/openGemini/pull/42.
