### ISSUE TITLE
page query did not return any result in several pages 分页查询在部分页面没有返回结果

### ISSUE THREAD

**Issue by KaguyaShinomiya** [openGemini/openGemini#418]
### Describe the bug（Bug 描述）

1. run query statement `SELECT * FROM "10260"`, the database will return a result set containing 1897 records;
2. run query statement `SELECT * FROM "10260" LIMIT 10 OFFSET 1600`, the result set contains 10 records;
3. yet when i ran query statement `SELECT * FROM "10260" LIMIT 10 OFFSET 1700`, the result set was empty.
4. The same bug also occurs in other pages or other measurements.
[New Connection_iot-platform-metric.csv](https://github.com/openGemini/openGemini/files/13110202/New.Connection_iot-platform-metric.csv)

### Screenshots（屏幕截图）

![a705e3eaa4139226a0dbdf03a6b72ae](https://github.com/openGemini/openGemini/assets/63454263/b674eac4-46f5-42e3-90f2-29b69e66d913)
![36ce54c7436c8119e6323c087a87ae6](https://github.com/openGemini/openGemini/assets/63454263/89124c8e-32b1-4b2e-bef8-520c078678cf)
![f781ef2ba6555f1f6b9cd5beeb80303](https://github.com/openGemini/openGemini/assets/63454263/e625fb0b-e790-4726-bfac-e4d7d6e5760b)
![68c8b8ae1d8100e2685a4a313ae5f8f](https://github.com/openGemini/openGemini/assets/63454263/a37731f5-e099-4099-bdd9-bf5be25d0384)

### Additional context（其他的一些补充内容）

OS: Linux
version: 1.1.0.rc1
single node

**Comment by xiangyu5632** [comment]
Don't you have a tag in your data?
