### ISSUE TITLE
使用java sdk存数据的时候，有时候会有json格式数据，里面带有换行符\n，这时候存入出错

### ISSUE THREAD

**Issue by Starry326** [openGemini/openGemini#425]
### Describe the bug（Bug 描述）

有时候需要存json格式数据，当json格式不换行时可以用java sdk正常存入，当json带有换行符\n时则不行。
如下两个字符串，s1不能存入，但s2可以正常存入。

String s1 = "{\n" +
                "  \"deviceId\": 2166,\n" +
                "  \"dataTime\": 1694482947700,\n" +
                "  \"values\":{\n" +
                "     \"temperature\": \"hhh\"\n" +
                "  }\n" +
                "}";
String s2 = "{\"deviceId\": 2166,\"dataTime\": 1694482947700,\"values\":{\"temperature\": \"hhh\"}}";

**Comment by xiangyu5632** [comment]
InfluxDB 的SDK自身问题，但这个问题社区打算在自研SDK中解决

**Comment by shoothzj** [comment]
track by #746
