### ISSUE TITLE
sherlock-enable监控cpu的算法需要优化

### ISSUE THREAD

**Issue by shuangquansq** [openGemini/openGemini#451]
### Describe the bug（Bug 描述）

实际环境即便把阈值进行了调整，cpu的堆栈信息还是打印频繁。原因是 cpu有瞬时波动。当前的算法是和前10次平均值进行比对后，如果current本次的波动符合diff的阈值，那么就打印堆栈。此算法在cpu瞬时波动时打印过于频繁。建议算法优化为连续采集cpu百分比，比如3次或者10次（建议是3次，或者可配置），其值都大于给定的min的阈值时，才进行堆栈打印。这样才能达到真正的监控目的。

### To Reproduce（Bug 复现步骤）

      [sherlock]
        sherlock-enable = true
        collect-interval = "10s"
        cpu-max-limit = 95
        dump-path = "/opt/dbs/logs"
      [sherlock.cpu]
        enable = true
        min = 60
        diff = 30
        abs = 99
        cool-down = "10m"
      [sherlock.memory]
        enable = true
        min = 30
        diff = 25
        abs = 70
        cool-down = "10m"
      [sherlock.goroutine]
        enable = true
        min = 1200
        diff = 20
        abs = 2000
        max = 5000
        cool-down = "30m"

### Screenshots（屏幕截图）

![image](https://github.com/openGemini/openGemini/assets/36983808/93ef4d8b-398c-4592-be64-760b3c478cd8)

**Comment by shilinlee** [comment]
修改点：
> 建议算法优化为连续采集cpu百分比10次，其值都大于给定的min的阈值

**Comment by wtsclwq** [comment]
I will support it.
