### ISSUE TITLE
Could you please help us provide SQL related to the management model

### ISSUE THREAD

**Issue by qianmoQ** [openGemini/openGemini#459]
### Describe your question

Since we want to support openGemini databases in datacap, we need to provide the following SQL templates for managing openGemini metadata in datacap and implementing Navicat-like functions.

- `SYSTEM_FOR_GET_ALL_DATABASES`
> MySQL example, please see https://github.com/devlive-community/datacap/blob/4551ef08aea8298969c6482e2e1442f8cd012c78/core/datacap-server/src/main/schema/1.15.0/schema.sql#L97

- `SYSTEM_FOR_GET_ALL_TABLES `
> MySQL example, please see https://github.com/devlive-community/datacap/blob/4551ef08aea8298969c6482e2e1442f8cd012c78/core/datacap-server/src/main/schema/1.15.0/schema.sql#L105

- `SYSTEM_FOR_GET_ALL_COLUMNS `
> https://github.com/devlive-community/datacap/blob/4551ef08aea8298969c6482e2e1442f8cd012c78/core/datacap-server/src/main/schema/1.15.0/schema.sql#L131

**Comment by xiangyu5632** [comment]
> SYSTEM_FOR_GET_ALL_DATABASES

show databases
> SYSTEM_FOR_GET_ALL_TABLES 

show measurements
> SYSTEM_FOR_GET_ALL_COLUMNS

show tag keys
show field keys

**Comment by xiangyu5632** [comment]
you can use docker to run openGemini and have a try, learn how it works
get start: https://docs.opengemini.org/guide/quick_start/get_started.html 

**HTTP API**
```
> curl -G 'http://localhost:8086/query?db=mydb' --data-urlencode 'q=show databases"'
```
