### ISSUE TITLE
某个节点sql.err.log一直尝试创建monitor库

### ISSUE THREAD

**Issue by fanzhongyu** [openGemini/openGemini#460]
### Describe your question

{"level":"error","time":"2024-01-15T10:45:23.637071908+08:00","msg":"query error! authorizing query","hostname":"***","error":"monitor not authorized to execute statement 'CREATE DATABASE monitor WITH DURATION 168h0m0s REPLICATION 1 NAME autogen', requires admin privilege","db":"","rError":"json: unsupported type: func() (io.ReadCloser, error)","userID":"monitor","location":"httpd/handler.go:567","repeated":1}
某个opengemini节点的sql.err.log日志中一直打印尝试创建monitor库，但是monitor库已经存在了

**Comment by fanzhongyu** [comment]
然后所有monitor的写入节点就是一直尝试打印日志的那台机器。我做过的操作只是把所有节点的monitor重启了一下，但是monitor库已经存在，并且现在监控数据可以查看

**Comment by xiangyu5632** [comment]
从报错来看，系统中有monitor用户，没有创建db的权限，可以检查一下

**Comment by xiangyu5632** [comment]
如果问题已的得到解决，请您反馈社区，以便及时关闭Issue

**Comment by fanzhongyu** [comment]
{"level":"error","time":"2024-01-15T11:29:50.597447783+08:00","msg":"ctx send fail","hostname":"***","query":"CREATE DATABASE monitor WITH DURATION 168h0m0s REPLICATION 1 NAME autogen","error":"retention policy conflicts with an existing policy","location":"query/executor.go:506","repeated":1}
{"level":"error","time":"2024-01-15T11:29:52.58725297+08:00","msg":"ctx send fail, ErrQueryAborted","hostname":"***","query":"CREATE DATABASE monitor WITH DURATION 168h0m0s REPLICATION 1 NAME autogen","location":"query/executor.go:502","repeated":1}
{"level":"error","time":"2024-01-15T11:29:52.665359226+08:00","msg":"ctx send fail","hostname":"***","query":"CREATE DATABASE monitor WITH DURATION 168h0m0s REPLICATION 1 NAME autogen","error":"retention policy conflicts with an existing policy","location":"query/executor.go:506","repeated":1}
{"level":"error","time":"2024-01-15T11:29:53.599406541+08:00","msg":"ctx send fail","hostname":"***","query":"CREATE DATABASE monitor WITH DURATION 168h0m0s REPLICATION 1 NAME autogen","error":"retention policy conflicts with an existing policy","location":"query/executor.go:506","repeated":1}
{"level":"error","time":"2024-01-15T11:29:56.852535514+08:00","msg":"ctx send fail, ErrQueryAborted","hostname":"***","query":"CREATE DATABASE monitor WITH DURATION 168h0m0s REPLICATION 1 NAME autogen","location":"query/executor.go:502","repeated":1}
权限问题已经解决了，但是我已经创建了moitor库，为什么ts-monitor还是要一直发送建库请求，日志一直打印库已存在

**Comment by fanzhongyu** [comment]
# ts-monitor向openGemini业务集群发送查询命令的时间间隔
  query-interval = "5m"
感觉可能跟这个配置有关，但是我使用的是默认配置5m，但是通过日志查看感觉像是5s就发送了一次查询请求

**Comment by shilinlee** [comment]
请修改ts-monitor配置文件，RP和duration修改为实际的值：

https://docs.opengemini.org/zh/guide/maintenance/monitor.html#%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B

<img width="933" alt="image" src="https://github.com/openGemini/openGemini/assets/22270117/b14916d2-8837-40b5-a190-c86fc51f46d6">
