### ISSUE TITLE
ts-sql和ts-store大批量写入测试

### ISSUE THREAD

**Issue by fanzhongyu** [openGemini/openGemini#463]
### Describe your question

我的集群规模是3个ts-sql和3个ts-store，但是插入的时候只写入到1个ts-sql和3ts-store，当我写入到60万个metrics/s（300行 * 2000个fields/s）的时候，通过监控发现ts-sql的写入速率一直在15-60w/s 波动，并且有1200ms-5000ms延迟，ts-store5-20w/S，延时在200-1500ms左右，并且通过监控发现数据写入成功率不能稳定在100%（大概是99.9999998%那种）
我想知道除了写入的时候负载均衡写在ts-sql上，还有没有别的配置可以增加ts-sql和ts-store的吞吐量的方法，因为我通过监控发现，内存和cpu并没有跑满

**Comment by shilinlee** [comment]
1. 第一个办法确实是需要利用好所有的ts-sql，增大ts-sql并发处理数据能力。
2. 数据写入是批量的吗？ 如果不是，请一个写请求，同时发送100/200/300(具体多少，可以实测一下效果最佳就行)行数据试试。
3. 我姑且认为你都是写入的同一个measurement，如果不是，则一个写请求请将相同的measurement排序挨着一起。
4. 同样，两千行的fields，请发送写请求前，请将fields按照**field_key**排序(字符串升序)。比如：
```console
mst,tag=demo a_field=xxx,b_field=xxx,c_field=xxx
```

改完后，欢迎反馈优化效果。🙂🙂🙂

**Comment by fanzhongyu** [comment]
好的，感谢反馈，我将尝试如下修改：
1、利用好所有的ts-sql，增加并发处理能力。
2、是批量写入，我尝试修改influxDb-java的actions和flushDuration来尝试获取最佳配置
3、是写入同一个measurement，然后我会按照fied字符串升序的方法插入Point builder fields的tree map再次尝试写入。

另外还有一个请教的地方，因为我使用的是默认配置，有没有配置，比如**增大内存，缓存，链接数**等方式，加大它批处理的能力来增加单ts-sql或者ts-store的处理能力。

**Comment by shilinlee** [comment]
先使用默认配置，具体调优，需要结合火焰图来分析。先看看改后的性能，再来分析哪里还有可以改善的空间。

**Comment by xiangyu5632** [comment]
一行数据2000列，这导致每一条数据都比较大，写入慢是可能的，因为涉及到网络传输等问题。

**Comment by fanzhongyu** [comment]
感谢回复，昨天测试的时候测试数据造错了，昨天tag数据每秒都是新的，就会造成频繁创建tag索引导致巨慢，其实真实的数据是设备稳定下来之后，tag不会大幅度变化或者增加的，所以导致测试数据异常导致写的速率过慢。
另外增加了一个ts-sql的负载均衡器之后，吞吐量有提升。
另外有一个问题是我统计了store的写入成功率，偶尔大批量写入的时候会出现0.9999999423555205这种成功率的情况，请问这是正常的吗

**Comment by fx408** [comment]
> 另外有一个问题是我统计了store的写入成功率，偶尔大批量写入的时候会出现0.9999999423555205这种成功率的情况，请问这是正常的吗

1. 建议做数据预热，并修改保策略，加大 INDEX DURATION

**Comment by fx408** [comment]
> 感谢回复，昨天测试的时候测试数据造错了，昨天tag数据每秒都是新的，就会造成频繁创建tag索引导致巨慢，其实真实的数据是设备稳定下来之后，tag不会大幅度变化或者增加的，所以导致测试数据异常导致写的速率过慢。 另外增加了一个ts-sql的负载均衡器之后，吞吐量有提升。 另外有一个问题是我统计了store的写入成功率，偶尔大批量写入的时候会出现0.9999999423555205这种成功率的情况，请问这是正常的吗

1. 建议做数据预热，并修改保策略，加大 INDEX DURATION
2. 成功率是如何统计的，写入过程有没有报错？

**Comment by fanzhongyu** [comment]
SELECT mean(writeOkCount)/mean(writeTotalCount) FROM io WHERE $timeFilter GROUP BY time(120s), hostname

**Comment by fanzhongyu** [comment]
数据成功率：SELECT mean(writeOkCount)/mean(writeTotalCount) FROM io WHERE $timeFilter GROUP BY time(120s), hostname

**Comment by fx408** [comment]
> 数据成功率：SELECT mean(writeOkCount)/mean(writeTotalCount) FROM io WHERE $timeFilter GROUP BY time(120s), hostname。另外数据预热是什么意思，怎么做的呢

SELECT  writeOkCount, writeTotalCount FROM io where time>now()-5m group by hostname

**Comment by fanzhongyu** [comment]
![image](https://github.com/openGemini/openGemini/assets/20722039/5d8b27ac-8a37-4921-b6e8-fb9d85720068)
确实会存在丢某条数据的问题呢，但是从数据量和横向拉通来说，丢失率还是不大的

**Comment by shilinlee** [comment]
> ![image](https://private-user-images.githubusercontent.com/20722039/297252114-5d8b27ac-8a37-4921-b6e8-fb9d85720068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjI4NDAsIm5iZiI6MTcwNTQ2MjU0MCwicGF0aCI6Ii8yMDcyMjAzOS8yOTcyNTIxMTQtNWQ4YjI3YWMtOGEzNy00OTIxLWI2ZTgtZmI5ZDg1NzIwMDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YjFjY2QyYjU1NjRmNWY1MmM2OTk1YWRmYTA0YmI3MGVlZTg4MTY2OGM4NGQ2NDM3NTEyZGY0OTgzMjhlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m9NTKrAgLrzNRougj6V0c2foFNuPc5L57MDORWS7dPs) 确实会存在丢某条数据的问题呢，但是从数据量和横向拉通来说，丢失率还是不大的

我看了下代码，没有丢失，writeOkCount, writeTotalCount 的计数是有先后顺序的，所以监控获取这两个参数就存在gap，是符合预期的。

<img width="913" alt="image" src="https://github.com/openGemini/openGemini/assets/22270117/a11c5c9c-cb51-4a0d-b96d-127110b4dad8">

**Comment by fanzhongyu** [comment]
所以通过监控图标获取到如果不是大幅度成功率波动可以理解为数据没丢失，或者说条数极其少的情况下。因为我统计的成功率就算不是100%也是99.99998%这种类似的

**Comment by xiangyu5632** [comment]
> 所以通过监控图标获取到如果不是大幅度成功率波动可以理解为数据没丢失，或者说条数极其少的情况下。因为我统计的成功率就算不是100%也是99.99998%这种类似的

可以这么理解

**Comment by fanzhongyu** [comment]
感谢各位帮助

**Comment by shilinlee** [comment]
写入错误，可通过这个监控指标查看：

```sql
SELECT last(write400ErrReq)-first(write400ErrReq) AS write_error FROM $database..\"httpd\" WHERE $timeFilter GROUP BY time(5m),hostname

SELECT last(write500ErrReq)-first(write500ErrReq) AS write_error FROM $database..\"httpd\" WHERE $timeFilter GROUP BY time(5m),hostname
```

**Comment by fanzhongyu** [comment]
后面我又继续压测，发现多线程小数据量插入比大数据量插入的效率是高的。比如12个线程，每个线程66w/s均匀写入ts-sql是比6个线程132w/s的效率好，但是随着数据持续增长，ts-sql的处理能力就下降。
当ts-sql负责的写入请求多的时候，ts-sql会成为瓶颈，时延非常的高，但是ts-store的时延不是很高，所以感觉是ts-sql时延造成的影响。
![image](https://github.com/openGemini/openGemini/assets/20722039/ca3d2c7f-e134-4390-a70c-3b8f9856ad99)
ts-sql请求时延：SELECT difference("writeReqDurationNs")/difference("writeReq")/1000000 AS "Duration" FROM httpd WHERE $timeFilter GROUP BY "hostname" FILL(null)
ts-sql存储时延：SELECT difference("writeStoresDurationNs")/difference("writeReq")/1000000 AS "Duration" FROM httpd WHERE $timeFilter GROUP BY hostname FILL(null)
但是我发现，cpu和内存都还有空余，那么如何增加单ts-sql的吞吐量呢，因为我想把cpu或者内存打满，我感觉还可以通过配置增加ts-sql的吞吐量

**Comment by shilinlee** [comment]
1. 每个请求batch多少行（每行多少列）
2. 只有写入是很难把CPU都吃满的，我们做了很多优化。查询才非常吃CPU

**Comment by fanzhongyu** [comment]
一个线程每次请求3000行，220列，其中1个tag。测试的是12个线程

**Comment by fanzhongyu** [comment]
单请求每批次数据太多了，降低成1000行，220列，1个tag从稳定性和效率有所提升了

**Comment by shilinlee** [comment]
你的ts-sql分配了几个核？

**Comment by fanzhongyu** [comment]
没有配置ts-sql分配的核数，因为我看官网你们会自动适配，但是3台服务器，每台服务器4核，我能否显式的配置common中cpu-num来超额使用cpu
