### ISSUE TITLE
关于gemini写入过程的请教

### ISSUE THREAD

**Issue by fanzhongyu** [openGemini/openGemini#464]
### Describe your question

1、关于seriesKey 的范围是怎么确定的，是SHARD DURATION吗？
2、如你们官网所说，一个store节点存放一个SHARD，比如我有三个节点，就有三个shard，那么新来一个tag是如何决定存入哪个shard的，或者说如何避免写入热点
3、比如我查询的时候既指定了tag，又指定了time，那么过程是通过tag找到tsids，然后通过tsid找到seriesKey 去筛选数据？还是tag找到tsids，seriesKey 找到tsids，取交集？这个过程是怎么样的呢
4、数据的写入是通过tag和time索引确定数据块顺序写入的吗？
5、单表tag索引如果多到一定程度会影响单表查询效率吗？

**Comment by xiangyu5632** [comment]
> ### Describe your question
> 1、关于seriesKey 的范围是怎么确定的，是SHARD DURATION吗？ 2、如你们官网所说，一个store节点存放一个SHARD，比如我有三个节点，就有三个shard，那么新来一个tag是如何决定存入哪个shard的，或者说如何避免写入热点 3、比如我查询的时候既指定了tag，又指定了time，那么过程是通过tag找到tsids，然后通过tsid找到seriesKey 去筛选数据？还是tag找到tsids，seriesKey 找到tsids，取交集？这个过程是怎么样的呢 4、数据的写入是通过tag和time索引确定数据块顺序写入的吗？ 5、单表tag索引如果多到一定程度会影响单表查询效率吗？

1. 数据写入时，每条数据通过hash方式，按seriesKey打散到不同的ts-store。SHARD DURATION是SHARD GROUP的时间范围，这里有数据保留时间与SHARD GROUP的对应时间范围关系：https://docs.opengemini.org/zh/guide/schema/retention_policy.html#shard-duration

**Comment by fanzhongyu** [comment]
理解了，感谢回答
