### ISSUE TITLE
Is there any open source code for tsbs? 请问是否有tsbs的开源代码?

### ISSUE THREAD

**Issue by timlincool** [openGemini/openGemini#502]
### Describe your question

Hello,

I discovered that TSBS is used for performance testing on https://docs.opengemini.org/zh/guide/introduction/performance.html. However, it seems that the specific code for using TSBS for testing is not provided. Is it because TSBS can be directly used for testing without any modifications to the code? If modifications are necessary, is there any open-source code available for these tests?

Thank you!

您好
我在 https://docs.opengemini.org/zh/guide/introduction/performance.html
发现了有使用tsbs作为性能测试, 但好像没找到使用tsbs的测试代码?
请问是因为可以直接使用tsbs来测试而不需要改代码吗?
如果需要改代码 ,是否有开源测试的代码?

谢谢!

**Comment by xiangyu5632** [comment]
The openGemini is compatible with the InfluxDB syntax and APIs. Therefore, we do not develop the tsbs test tool of the openGemini. Instead, we use the tsbs test program of the InfluxDB to perform the performance test.

openGemini 兼容 InfluxDB 语法和接口API，因此我们并没有单独开发openGemini的tsbs测试工具，而是直接使用Influxdb的tsbs测试程序进行的性能测试。

**Comment by timlincool** [comment]
好的 谢谢
