### ISSUE TITLE
tag array not working

### ISSUE THREAD

**Issue by localvar** [openGemini/openGemini#507]
### Describe the bug（Bug 描述）

I follow [this document](https://docs.opengemini.org/zh/guide/features/tag_array.html) to try the tag array feature, but the examples are not working as expected.

### To Reproduce（Bug 复现步骤）

```shell
> create database db0
> use db0
> insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
ERR: error parsing query: syntax error: unexpected IDENT
```

### Expected behavior（期望结果）

3 records been written to the database

**Comment by supercz** [comment]
to use tag array feature, should create database like this:
```
> create database db0 tag attribute array
> use db0
> insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
> select * from cpu
name: cpu
time                tk1    tk2      tk3      value
----                ---    ---      ---      -----
1670491329000000000 value1 value2   value3   2
1670491329000000000 value1 value22  value33  2
1670491329000000000 value1 value222 value333 2
```
@xiangyu5632 Please update the doc. https://docs.opengemini.org/zh/guide/features/tag_array.html

**Comment by xiangyu5632** [comment]
> to use tag array feature, should create database like this:
> 
> ```
> > create database db0 tag attribute array
> > use db0
> > insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
> > select * from cpu
> name: cpu
> time                tk1    tk2      tk3      value
> ----                ---    ---      ---      -----
> 1670491329000000000 value1 value2   value3   2
> 1670491329000000000 value1 value22  value33  2
> 1670491329000000000 value1 value222 value333 2
> ```
> 
> @xiangyu5632 Please update the doc. https://docs.opengemini.org/zh/guide/features/tag_array.html

tkx @supercz， after I update the document， I‘ll feedbacks here

**Comment by localvar** [comment]
this should be updated too: https://docs.opengemini.org/zh/guide/schema/database.html#create-database-%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E5%BA%93

**Comment by localvar** [comment]
hmm, seems still not working with 'tag attribute array'

```shell
> create database db0 tag attribute array
> use db0
> insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
ERR: error parsing query: syntax error: unexpected IDENT
> select * from cpu
ERR: measurement not found
```

I tried on below two versions:

```shell
$ ./ts-cli version
openGemini version info:
ts-cli: 1.1.0~rc1
git: main 222f626c7cf22b8a90983bd84cf5fc7e4969ef6c
os: linux
arch: amd64
```

```shell
$ ./ts-cli version
2024/02/29 11:06:39 proto: duplicate proto type registered: influxql.Measurements
2024/02/29 11:06:39 proto: duplicate proto type registered: influxql.Measurement
openGemini version info:
ts-cli: v1.1.1
git: HEAD bde0e11a903a87811ed3d92b5dc6f1f1c6f6713f
os: linux
arch: amd64
```

@supercz

**Comment by localvar** [comment]
hmm, seems still not working with 'tag attribute array'

```shell
> create database db0 tag attribute array
> use db0
> insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
ERR: error parsing query: syntax error: unexpected IDENT
> select * from cpu
ERR: measurement not found
```

I tried on below two versions:

```shell
$ ./ts-cli version
openGemini version info:
ts-cli: 1.1.0~rc1
git: main 222f626c7cf22b8a90983bd84cf5fc7e4969ef6c
os: linux
arch: amd64
```

```shell
$ ./ts-cli version
2024/02/29 11:06:39 proto: duplicate proto type registered: influxql.Measurements
2024/02/29 11:06:39 proto: duplicate proto type registered: influxql.Measurement
openGemini version info:
ts-cli: v1.1.1
git: HEAD bde0e11a903a87811ed3d92b5dc6f1f1c6f6713f
os: linux
arch: amd64
```

@supercz

**Comment by xiangyu5632** [comment]
firstly, delete database `db0`， and then create it again using `create database db0 tag attribute array`

**Comment by localvar** [comment]
> firstly, delete database `db0`， and then create it again using `create database db0 tag attribute array`

@xiangyu5632 I haven't paste that statement, but I did it.

**Comment by xiangyu5632** [comment]
> this should be updated too: https://docs.opengemini.org/zh/guide/schema/database.html#create-database-%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E5%BA%93

okay, right

**Comment by xiangyu5632** [comment]
>
> create database db0 tag attribute array
> insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
ERR: error parsing query: syntax error: unexpected IDENT

before inserting, maybe you missed `use db0`

**Comment by localvar** [comment]
> > create database db0 tag attribute array
> > insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
> > ERR: error parsing query: syntax error: unexpected IDENT
> 
> before inserting, maybe you missed `use db0`

no, that's not the case, this is a mistake when I want to show you the result of `show databases`, I have `use db0` before.
and below is the result after I delete the data files and restart the server:

```shell
$ ./ts-cli
openGemini CLI 0.1.0 (rev-revision)
Please use `quit`, `exit` or `Ctrl-D` to exit this program.
> show databases
name: databases
+------+
| name |
+------+
+------+
1 columns, 0 rows in set

> create database db0 tag attribute array
> use db0
> insert cpu,tk1=value1,tk2=[value2,value22,value222],tk3=[value3,value33,value333] value=2 1670491329000000000
ERR: error parsing query: syntax error: unexpected IDENT
```

note it says "error parsing query", that's should happen before it checks `db0` attributes.

**Comment by xiangyu5632** [comment]
@supercz  please check it， Why is there a grammar error?

**Comment by xiangyu5632** [comment]
@localvar  mmm， I found it!

**Comment by xiangyu5632** [comment]
I have updated the documents
reference: 
https://docs.opengemini.org/zh/guide/features/tag_array.html#%E5%86%99%E5%85%A5%E6%B5%81%E7%A8%8B
https://docs.opengemini.org/zh/guide/schema/database.html#%E7%A4%BA%E4%BE%8B
