### ISSUE TITLE
ts-cli commnad line text often corrupt when moving the caret in a histroy command

### ISSUE THREAD

**Issue by localvar** [openGemini/openGemini#519]
### Describe the bug（Bug 描述）

We often need to use/edit a history command, but in 'ts-cli', the command line text often corrupt when moving the caret.
I've never seen this from other applications, so I think it is a bug of 'ts-cli'.

### To Reproduce（Bug 复现步骤）

1. start `ts-cli` and execute some commands
2. using the UP/DOWN keys to select a history command.
3. using the LEFT/RIGHT keys to move the caret, note to **keep the key pressed**.
4. the command line text corrupt like below, and user is forced to reenter the full command.
```shell
> insert cpu,host=server-01,region=south-cn disk=11,memory=12,network=13
ERR: {"error":"partial write: field type conflict: input field \"network\" on measurement \"cpu\" is type float, already exists as type integer dropped=1"}

> > > > > > > > > > > > > > > insert cpu,host=server-01,region=south-cn disk=11,memory=12,netwo?[D?[Drk=13
ERR: {"error":"partial write: field type conflict: input field \"memory\" on measurement \"cpu\" is type float, already exists as type integer dropped=0"}

> > > > insert cpu,host=server-01,region=south-cn disk=11,memory=12,netwo?[D?[Drk=13
ERR: {"error":"partial write: field type conflict: input field \"memory\" on measurement \"cpu\" is type float, already exists as type integer dropped=0"}
```

**Comment by localvar** [comment]
seems the issue only occur when using `ts-cli` in [tmux](https://github.com/tmux/tmux).

**Comment by xiangyu5632** [comment]
> seems the issue only occur when using `ts-cli` in [tmux](https://github.com/tmux/tmux), but as tmux is such a widely used tool, I propose to check the root cause and make `ts-cli` compatible with `tmux`.

I'm asking if other developers are willing to fix this bug

**Comment by StepY1aoZz** [comment]
Seems that this bug is caused by the package `go-prompt` rather than `ts-cli` itself. (ref https://github.com/c-bata/go-prompt/issues/119 and https://github.com/c-bata/go-prompt/issues/223 .)  
Since the repo `go-prompt` is no longer maintained, I fix this bug in my own fork as a temporary workaround. But replacing the deprecated `go-prompt` in the future might be a better choice.
