### ISSUE TITLE
Could UT for draft PRs be enabled?

### ISSUE THREAD

**Issue by localvar** [openGemini/openGemini#541]
### Describe your question

I found UT for draft PRs is disabled in this repo, but I think it will be useful if enabled.

I often submit a draft PR, leave github to run the tests, work on othe tasks myself, and come back later to check the test results, make changes if something is wrong or make the PR "ready for review" if everything looks good.

I think the above practice is reasonable, so could UT for draft PRs be enabled in this repo? or is there anything preventing it is been enabled?

**Comment by xiangyu5632** [comment]
mm.. I haven't found some way to enable draft PR, and It works refer to #543 which modifies UT

**Comment by localvar** [comment]
I think it is disabled here:

https://github.com/openGemini/openGemini/blob/e36de0400964130330888756251c44731f08f164/.github/workflows/ci.yml#L70

and here:

https://github.com/openGemini/openGemini/blob/e36de0400964130330888756251c44731f08f164/.github/workflows/ci.yml#L97

by PR #254 .

> mm.. I haven't found some way to enable draft PR, and It works refer to #543 which modifies UT maybe it is enabled by default

**Comment by shoothzj** [comment]
Does it really matters? Contributors also can mark the title as [WIP] to trigger the ci. I don't think it really matters.

**Comment by localvar** [comment]
It is not "really matters" because there are other solutions always.
But it is a more formal process then "WIP": draft PRs can never be merged by a mistake. I think this is why github has this feature.

> Does it really matters? Contributors also can mark the title as [WIP] to trigger the ci. I don't think it really matters.

**Comment by xiangyu5632** [comment]
ref #545
