### ISSUE TITLE
optimize repo size, it has reached 94M

### ISSUE THREAD

**Issue by xuthus5** [openGemini/openGemini#544]
### Describe your question

optimizing the repository size? 087a35bb has introduced the build folder and it has been removed in bca7e9cc.

**Comment by xiangyu5632** [comment]
sure

**Comment by localvar** [comment]
> sure

but this is impossible unless rewrite the git history, which result in a very very big impaction...

**Comment by shoothzj** [comment]
We will not modify the git history because there are many downstream consumers of our repo.
