### ISSUE TITLE
openGemini Q&A

### ISSUE THREAD

**Issue by xiangyu5632** [openGemini/openGemini#59]
If you have any questions about the installation and deployment of openGemini, syntax usage, or anything else, you can ask here.
![Q A](https://user-images.githubusercontent.com/49023462/199666269-78bc6f87-1437-406d-a98d-ee96eff9c1c1.PNG)

**Comment by xiangyu5632** [comment]
Question：Why does the data and wal folders not exist in the ts-store data directory after a small amount of data is written?
Answer：It's normal.
In a single-node, this problem does not occur.
In a cluster, only a small amount of data is written and all data may store on one node of the cluster. As a result, other nodes do not have data, and no data and wal directories exist. The two directories exist on the node where the data is stored.

**Comment by xiangyu5632** [comment]
**问题现象：** K8s（KubeEdge）部署，8010端口起不来
**问题原因：** 
定位方法：
1. 检查配置文件是否正确，如果不正确，修改正确后，清空ts-store、ts-meta的数据目录，再重新拉起 --结束
2. 如果全部配置文件是正确的：访问任意一个meta节点，

**Comment by zhouyu222** [comment]
唯一管理员应该怎么创建？
![image](https://user-images.githubusercontent.com/65350824/227470518-3d22cd48-9da1-4ed1-a104-ef5c361c8192.png)

**Comment by xiangyu5632** [comment]
> 
参考文档 https://docs.opengemini.org/zh/guide/security_user/user_manage.html

**Comment by shoothzj** [comment]
move to here: https://github.com/openGemini/openGemini/discussions
