### ISSUE TITLE
CentOS7.6部署v1.2.0使用ts-cli输入认证信息无反应且无法认证成功

### ISSUE THREAD

**Issue by zealzhangz** [openGemini/openGemini#594]
### Describe the bug（Bug 描述）

使用社区二进制版本openGemini-1.2.0-linux-amd64在CentOS Linux release 7.6. 上部署成功后，使用自带的ts-cli工具集群认证，连接使用输入用户名无反应，多次输入回车命令行界面显示异常，退出ts-cli后发现Linux shell 回车也会显示异常，经测试目前使用v1.1.1正常。如下图：
<img width="514" alt="image" src="https://github.com/openGemini/openGemini/assets/8454011/2834ad3e-ed71-42da-9453-69d1655a1771">

社区其他群友反馈，,windows上使用正常，银河麒麟 4.19.90-52.22.v2207.ky10.x86_64使用和CentOS 7.6 异常信息一致，使用不正常，如下图：
![image](https://github.com/openGemini/openGemini/assets/8454011/c8c01221-3777-4f93-87cf-2672639405b0)

### To Reproduce（Bug 复现步骤）

1. 使用二进制版本（openGemini-1.2.0-linux-amd64）部署
2. 使用ts-cli连接集群
3. 使用auth命令进行认证，回车再现问题

### Expected behavior（期望结果）

使用ts-cli连接集群，auth命令进行认证正常，访问集群正常

### Screenshots（屏幕截图）

<img width="832" alt="image" src="https://github.com/openGemini/openGemini/assets/8454011/9cd99a1c-c2fb-4c64-a79f-79bd6ec6135f">

**Comment by xiangyu5632** [comment]
This issue is caused by go-prompt
Thanks to @xuthus5 for the demo program, which can reproduce the problem stably

```
package main

import (
	"fmt"
	"os"

	"github.com/c-bata/go-prompt"
	"golang.org/x/term"
)

func main() {
	var pr *prompt.Prompt
	pr = prompt.New(
		func(_ string) {
			fmt.Printf("username: ")
			var username string
			fmt.Scanf("%s\n", &username)
			if username == "exit" {
				os.Exit(0)
			}
			fmt.Printf("Enter your password: ")
			password, err := term.ReadPassword(int(os.Stdin.Fd()))
			if err != nil {
				panic(err)
			}
			fmt.Printf("username: %s, password: %s\n", username, password)
		},
		func(d prompt.Document) []prompt.Suggest {
			return nil
		},
	)
	pr.Run()
}
```

**Comment by StepY1aoZz** [comment]
@xiangyu5632 Could you please assign this issue to me?

**Comment by xuthus5** [comment]
Suggest fork `c-bata/go-prompt` to the openGemini org.

**Comment by shoothzj** [comment]
@StepY1aoZz I have assigned this issue to you, have fun

**Comment by shoothzj** [comment]
@xuthus5 Could you please seek for any alternatives?

**Comment by StepY1aoZz** [comment]
I have made some changes in the `go-prompt` repo and now the behavior of `auth` looks good in my terminal (zsh+Konsole). Maybe someone else could try this to see whether the fix is really working in different environment? Please see [#1](https://github.com/openGemini/go-prompt/pull/1) for detailed info.

**Comment by StepY1aoZz** [comment]
> Can you verify it in the `bash` environment? This is most of the scene.

Also looks good in bash.
