### ISSUE TITLE
count函数在查询多表时数据不准确

### ISSUE THREAD

**Issue by iftrue-cn** [openGemini/openGemini#620]
### Describe the bug（Bug 描述）

count函数在查询多表时数据不准确，多次查询返回结果不一致

### To Reproduce（Bug 复现步骤）

1. 导入示例数据
2. use NOAA_water_database
3. 同时查询两张表
![image](https://github.com/openGemini/openGemini/assets/23302166/35bce76d-44f1-4b17-904e-1f60bb6c69b9)
4. 同时查询所有表
![image](https://github.com/openGemini/openGemini/assets/23302166/1cfda504-7374-45eb-8030-c47ffc5bc722)

### Expected behavior（期望结果）

数据统计准确

**Comment by xiangyu5632** [comment]
count是可能出现不准确的情况，可以使用如下sql语句做count精确查询
```
SELECT  /*+ Exact_Statistic_Query */ count(*) FROM average_temperature
```
" /*+ Exact_Statistic_Query */ " 是关键字

**Comment by iftrue-cn** [comment]
> count是可能出现不准确的情况，可以使用如下sql语句做count精确查询
> 
> ```
> SELECT  /*+ Exact_Statistic_Query */ count(*) FROM average_temperature
> ```
> 
> " /*+ Exact_Statistic_Query */ " 是关键字

感谢解答，如果是单表查询count，是否会出现不准确的情况？
