### ISSUE TITLE
`show measurements` should return retention policy information

### ISSUE THREAD

**Issue by localvar** [openGemini/openGemini#640]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

currently, the `show measurement` statement returns measurements from all retention policies, without the retention policy information, this result in two issues:

* it is hard to understand which retention policy a measurement belongs to.
* if there measurement with same name in different retention policies, only one will be listed.

### Describe the solution you'd like（问题的解决办法是什么）

include retention policy information in the output of `show measurements`

**Comment by localvar** [comment]
I propose `show measurements` command to return more information, such as column definitions, shard keys(I found there's an undocumented `show measurement schema`, but seems it is not usable) and etc.

currently, users need to merge the output of two or more commands to get these information, this is not user friendly and also make these command less useful.

**Comment by xiangyu5632** [comment]
1. 不影响对InfluxDB兼容性，show measurements 自身命令上做修改

**Comment by StepY1aoZz** [comment]
Hi @localvar, thanks for proposing this issue. Considering the compatibility of InfluxDB, I think it would be better to not changing the return value of `SHOW MEASUREMENTS` . Instead, we could use a new command which return a more detailed schema information. I've proposed a possible implement in discussion https://github.com/openGemini/openGemini/discussions/706, maybe you could take a look and give us advice there?
