### ISSUE TITLE
同一句sql每次查询出来的数据都不一样（没有数据在写入）

### ISSUE THREAD

**Issue by harry97** [openGemini/openGemini#697]
### Describe the bug（Bug 描述）

相同的一句sql，会执行出三种结果，但是也只有三种，无论点多少次，就是在这三种情况返回。

### To Reproduce（Bug 复现步骤）

1.建库：CREATE DATABASE "activiti_myself" WITH REPLICATION 1 SHARD DURATION 8760h INDEX DURATION 8760h NAME "rp12month"。一年分一片。

2.建表：CREATE MEASUREMENT MyselfTackle WITH INDEXTYPE text INDEXLIST title，因为我怀疑过是不是INDEXTYPE 的问题，所以我还试过CREATE MEASUREMENT MyselfTackle这种建表方法，但是结果都是一样的，所以应该不是这个问题。

3.写入数据后的表结构：
tag列：
![image](https://github.com/user-attachments/assets/e69ed0a6-f2e2-49cc-8b66-38768f06319e)
field列：
![image](https://github.com/user-attachments/assets/b8d741c2-afa1-4e5e-8086-5b7f7422f425)
4.写入数据后的shard情况：
![image](https://github.com/user-attachments/assets/c11ba909-6f63-4ada-b586-e059a619202b)
5.留存策略：
![image](https://github.com/user-attachments/assets/34acb3ba-df3a-4f77-80b9-dbc499da7a19)

6.执行sql：
条件查询：同一个sql，三次执行，返回的条数，内容都不一样
![image](https://github.com/user-attachments/assets/ea26437e-d28a-4a08-ba0d-d84af1805e95)
查询总数：总数的查询多次点击下来倒是没有问题
![image](https://github.com/user-attachments/assets/d8cdc7ee-2876-4887-bd69-d8c5390cc987)

### Expected behavior（期望结果）

同一句sql的执行，应该只有一个结果集才对。感觉可能是改了分片时间跨度引起的，因为测过好几个条件，都是一样的会返回3种结果，分片也刚好是三片

**Comment by xiangyu5632** [comment]
麒麟操作系统下，可能存在各种不能预知的问题
