### ISSUE TITLE
启动openGemini失败

### ISSUE THREAD

**Issue by xiaoxiongw** [openGemini/openGemini#702]
### Describe the bug（Bug 描述）

断电或磁盘满之后，启动openGemini失败，重新清理磁盘之后，依然启动失败

### Screenshots（屏幕截图）

![25a1692f4de9c072e9f883875154d56](https://github.com/user-attachments/assets/a49b6b41-b02e-4b25-9d09-5c2e75bbefe3)

### Logs（完整的错误日志）

[single.error.log](https://github.com/user-attachments/files/16610751/single.error.log)

**Comment by xiangyu5632** [comment]
data/niescloud_iot/0/beta1500_autogen/593_1722816000000000000_1723420800000000000_593/tssp/ycsampledata_0000/out-of-order/00001126-0000-00000000.tssp，掉电或者磁盘满了使得该文件的写入受阻，导致文件完整性被损坏。
