### ISSUE TITLE
different results will be returned in writing expired data with rp key or not

### ISSUE THREAD

**Issue by Chenxulin97** [openGemini/openGemini#711]
### Describe the bug（Bug 描述）

Writing expired data(the database have only one retention policy, it's default),with rp key in url or not will return different results.

### To Reproduce（Bug 复现步骤）

1.write expired data by api with no rp key in url, like this:
`curl -i -XPOST "http://localhost:8086/write?db=science_is_cool"`
the server will return No Content(204)
2.write expired data by api with empty value rp  in url, like this:
`curl -i -XPOST "http://localhost:8086/write?db=science_is_cool&rp="`
the server will return Bad Request(400)

### Expected behavior（期望结果）

It should perform as the same when url with no rp or with empty value rp.

### Screenshots（屏幕截图）

![image](https://github.com/user-attachments/assets/6e8220e7-93ea-4cee-abea-2981e582896b)
![image](https://github.com/user-attachments/assets/cc1b5a31-5f23-40ce-ad90-fe0c8ba0c38c)

### Logs（完整的错误日志）

{"level":"error","time":"2024-08-23T09:12:13.303631974Z","msg":"write failed","hostname":"127.0.0.1:8400","error":"point time is expired, compared with rp duration","point time":1716196335997250700,"duration min":1716628333000000000,"time range":null,"errno":"40215013","location":"coordinator/points_writer.go:381","repeated":1}
{"level":"error","time":"2024-08-23T09:12:13.303763885Z","msg":"write point rows failed","hostname":"127.0.0.1:8400","db":"db_testProjectId","rp":"","error":"partial write: point time is expired, compared with rp duration dropped=1","location":"coordinator/points_writer.go:238","repeated":1}
{"level":"error","time":"2024-08-23T09:12:15.17352253Z","msg":"write Partial Write error:WritePointsWithContext","hostname":"127.0.0.1:8400","error":"point time is expired, compared with rp duration","db":"db_testProjectId","errno":"40215013","location":"httpd/handler.go:1016","repeated":1}

**Comment by Chenxulin97** [comment]
@xiangyu5632 @shoothzj

**Comment by xuthus5** [comment]
from `ts-server` , I didn't reproduce the problem.
```shell
create database expdb0
create retention policy one_day on expdb0 duration 1d replication 1 default
```

curl write expired data:
```curl
curl --request POST \
  --url 'http://localhost:8086/write?db=expdb0' \
  --header 'content-type: text/plain' \
  --data 'INSERT weather,location=us-midwest temperature=82 1465839830200400200'
```

got:
```
> POST http://localhost:8086/write?db=expdb0&rp
> content-type: application/x-www-form-urlencoded
> data ""
< 204 No Content
< content-type: application/json
< request-id: 7842be51-6148-11ef-800c-2cf05d627ea5
< x-geminidb-build: OSS
< x-geminidb-version:
< x-request-id: 7842be51-6148-11ef-800c-2cf05d627ea5
< date: Fri, 23 Aug 2024 12:08:55 GMT
```

curl write  expired data with empty rp

```curl
curl --request POST \
  --url 'http://localhost:8086/write?db=expdb0&rp=' \
  --header 'content-type: text/plain' \
  --data 'INSERT weather,location=us-midwest temperature=82 1365839830200400200'
```

got:
```
> POST http://localhost:8086/write?db=expdb0&rp
> content-type: application/x-www-form-urlencoded
> data ""
< 204 No Content
< content-type: application/json
< request-id: 0ab5cef5-6149-11ef-800d-2cf05d627ea5
< x-geminidb-build: OSS
< x-geminidb-version:
< x-request-id: 0ab5cef5-6149-11ef-800d-2cf05d627ea5
< date: Fri, 23 Aug 2024 12:13:01 GMT
```

**Comment by Chenxulin97** [comment]
I made some mistakes when checking expired data writing. The server performs the same way wether writing with rp key or not.
