### ISSUE TITLE
The `LIMIT` clause and `OFFSET` clause in `SHOW MEASUREMENTS` command are not working 

### ISSUE THREAD

**Issue by StepY1aoZz** [openGemini/openGemini#712]
### Describe the bug（Bug 描述）

As the document [SHOW MEASUREMENT](https://docs.opengemini.org/guide/schema/measurement.html#show-measurements) said, the `LIMIT` clause and `OFFSET` clause in `SHOW MEASUREMENTS` command are supported, but these two clause are not working. The database always return all the rows even if the `LIMIT` or `OFFSET` clause is specified.

By reviewing the code, I found the logic of processing offset and limit are missed:
https://github.com/openGemini/openGemini/blob/b3a161de2e8735997abb927182ab9fd651d9d9d2/lib/util/lifted/influx/coordinator/statement_executor.go#L1374-L1403

### Screenshots（屏幕截图）

```
> show measurements
name: measurements
+------+
| name |
+------+
| cpu  |
| mst  |
+------+
1 columns, 2 rows in set

> show measurements limit 1
name: measurements
+------+
| name |
+------+
| cpu  |
| mst  |
+------+
1 columns, 2 rows in set

> show measurements offset 1
name: measurements
+------+
| name |
+------+
| cpu  |
| mst  |
+------+
1 columns, 2 rows in set


```

**Comment by xiangyu5632** [comment]
Yes, it is not implemented. Would you like to try it?

**Comment by StepY1aoZz** [comment]
I'd love to.
