### ISSUE TITLE
COUNT(DISTINCT()) 去重计数查询临时表无效

### ISSUE THREAD

**Issue by zhj0811** [openGemini/openGemini#730]
### Describe the bug（Bug 描述）

去重计数在子查询中无效，返回NULL

![image](https://github.com/user-attachments/assets/d3f0b628-b483-486b-bba1-c4a766571288)

### To Reproduce（Bug 复现步骤）

查询monitor数据库中io表
select count(DISTINCT(ReadData16KBCount)) from io  #sql有效
select count(DISTINCT(ReadData16KBCount)) from (select * from io) #sql返回null
select count(ReadData16KBCount) from (select distinct(ReadData16KBCount) as ReadData16KBCount from (select * from io) limit 10) # sql返回正确
select count(ReadData16KBCount) from (select distinct(ReadData16KBCount) as ReadData16KBCount from (select * from io)) #sql返回null

**Comment by MrSanZhi** [comment]
Thanks for your feedback. 
This issue has been resolved and is related to the pushdown optimization of the distinct subquery operator and will be incorporated in the near future.
