### ISSUE TITLE
the implementation of 'store-path' option for 'monitor' is incorrect

### ISSUE THREAD

**Issue by localvar** [openGemini/openGemini#742]
### Describe the bug（Bug 描述）

the [documentation ](https://docs.opengemini.org/zh/guide/maintenance/monitor.html#%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B)
says, if we use below configuration, openGemini will write metric data to file `/tmp/openGemini/metric/metric.data`.
```toml
[monitor]
  store-path = "/tmp/openGemini/metric/metric.data"
```
however, this is wrong, openGemini actually write metric data to files in directory `/tmp/openGemini/metric/` with other names.

and from the `ts-monitor` configuration example in the above link, it says `metric-path` should be identical with `store-path` above.
however, its value should be `/tmp/openGemini/metric/`.

very confusing.

**Comment by xiangyu5632** [comment]
right, tks

see [https://github.com/openGemini/openGemini.github.io/pull/132](https://github.com/openGemini/openGemini.github.io/pull/132)
