### ISSUE TITLE
1.2和1.3版本同一条sql在使用相同的influxdb驱动下，返回不同的结果

### ISSUE THREAD

**Issue by tgde-github** [openGemini/openGemini#747]
### Describe the bug（Bug 描述）

我们在使用openGemini1.2和1.3版本，用influxDB的驱动，同样的代码，代码里面执行select count(id) from "device_log_tcp-client" where "deviceId" = '104-00001' and "deviceId" = '104-00001' tz('Asia/Shanghai')的，上述1.2版本返回的是1970-01-01T00:86:02， 而1.3版本返回的是0，但是在cli上执行，结果都是返回的0

### Expected behavior（期望结果）

1.2和1.3返回结果保持一致

### Screenshots（屏幕截图）

<img width="1547" alt="7900cf340588282e081eee2230a01ce" src="https://github.com/user-attachments/assets/7f76bd7e-356c-4184-9caf-a1add651708d">
<img width="1631" alt="216839016398c4c01c7a637954328b1" src="https://github.com/user-attachments/assets/3a67593e-d388-4848-a6e3-62d4492a97e8">
<img width="911" alt="3bd3b3c995f9f1cde2e01d75a8111ef" src="https://github.com/user-attachments/assets/7eb030c1-15a2-41f9-8933-4d29b8bc3087">

**Comment by xuthus5** [comment]
When an aggregate function is used in the opengemini, the `time` column is replaced with 0.

**Comment by zhiheng123** [comment]
opengemini的官方客户端不会去修改原始数据，欢迎使用[opengemini的java客户端](https://github.com/openGemini/opengemini-client-java)。 也可以联系我或者其他小伙伴协助你。
