### ISSUE TITLE
go1.23 build fail 

### ISSUE THREAD

**Issue by xwyzsn** [openGemini/openGemini#750]
### Describe your question

error message
```
[ERROR] run: Command 'GOOS=linux GOARCH=amd64 go build -mod=mod -o /root/open_gemini/src/openGemini/build/ts-cli -ldflags="-X github.com/openGemini/openGemini/app.Version=1.2.0 -X github.com/openGemini/openGemini/app.GitBranch=main -X github.com/openGemini/openGemini/app.GitCommit=8797d1e89fa48271f6e6428de97e2ee83d57ea99" ./app/ts-cli' failed with error: b'# github.com/openGemini/openGemini/app/ts-cli\nlink: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet\n'
```

go version go1.23.1 linux/amd64
related to [sonic ](https://github.com/bytedance/sonic/issues/660). Upgrade to sonic 1.12.2 may fix the problem. 

Besides, should we check the `content` type in [build.py](https://github.com/openGemini/openGemini/blob/main/build.py#L407) since `content` may be bytes.

**Comment by xuthus5** [comment]
Welcome to submit pr.

**Comment by xiangyu5632** [comment]
Do you know if the go version go1.20 can compile Sonic v1.12.2?

**Comment by xwyzsn** [comment]
> Can the go version go1.20 compile Sonic v1.12.2? We will not upgrade the Go version to v1.23 for system stability unless some necessary third-party components are imported and a later Go version is required.

Yes, sonicv1.12.2 can use go1.20. My understanding is that we just need to bump the version to avoid some errors caused by sonic when compiling with go1.23.

**Comment by xiangyu5632** [comment]
Okay, but I think it's necessary to limit the minimum version of Go used in the "go.mod" file because the third-party components we imported require Go v1.20.
In your PR, I think we should not remove the Go version.
