### ISSUE TITLE
【prometheus远程读写】只能查询到time为几天前的数据，无法查到time是最近时间的数据

### ISSUE THREAD

**Issue by xiaoliang-liu** [openGemini/openGemini#757]
### Describe the bug（Bug 描述）

我使用的是【prometheus远程读写】功能，在使用prometheus连接到openGemini后，使用SQL向openGemini中插入2条数据，接着在prometheus自带的web ui中查询数据，只能查询到一条数据，不符合预期。

### To Reproduce（Bug 复现步骤）

1. 我使用prometheus连接openGemini上；
2. 使用SQL语句 ```INSERT device1,__name__=device1,instance=localhost:9090,job=prometheus value=220.32 1727148666580000000和INSERT device1,__name__=device1,instance=localhost:9090,job=prometheus value=221.32 1726803355000000000```插入两条数据；
3. 在prometheus自带的web ui中查询数据，只能查询到一条时间较远的数据；

### Expected behavior（期望结果）

查询到两条数据

### Screenshots（屏幕截图）

<img width="793" alt="image" src="https://github.com/user-attachments/assets/27ab7f25-e18e-4490-80eb-1062d0a38d0e">
<img width="1565" alt="image" src="https://github.com/user-attachments/assets/8227bf7b-1e6a-4826-8e42-d4ac2db0bfc1">
<img width="832" alt="image" src="https://github.com/user-attachments/assets/ce3d14b9-cd41-4c8e-8b31-3cb044dd9195">

配置信息
<img width="808" alt="image" src="https://github.com/user-attachments/assets/15dce82f-85d3-4ccb-8d25-9e3602162087">
<img width="800" alt="image" src="https://github.com/user-attachments/assets/1b7ad09b-6b11-41de-8a4b-ccd94dc874ab">
<img width="853" alt="image" src="https://github.com/user-attachments/assets/8d706309-ecbe-40ed-b6bd-645ac1c2e5ef">
<img width="594" alt="image" src="https://github.com/user-attachments/assets/d362af06-1ea9-42b6-bad3-645db0494fb2">

### Additional context（其他的一些补充内容）

版本

1. openGemini1.2.0和openGemini1.3.0都尝试过；
2. prometheus-2.53.2和prometheus-2.54.1都尝试过；

**Comment by MrSanZhi** [comment]
Thank you very much for your feedback. 
When reproducing the problem, pay attention to the prom query time range. device1[10d] indicates the time range from now-10d to now. 
Check whether the data points that are not queried are within the time range.
Currently, promql is supported. You'd better use promql to query openGemini for better performance.
