### ISSUE TITLE
ts-cli 异常问题

### ISSUE THREAD

**Issue by imoxuan** [openGemini/openGemini#760]
### Describe the bug（Bug 描述）

ts-cli 退出后，回车之后异常

### To Reproduce（Bug 复现步骤）

1.下载openGemini-1.2.0-linux-amd64.tar.gz 
2.解压缩指定目录，opengemini
3.进入opengemini/usr/bin
4.启动./ts-server
5.新开一个窗口，运行./ts-cli
6.按照提示输入quit
7.这个时候按回车键，理论上就是新开一行显示。但是，现在不是新启动一行，而是在一行是显示，如图

以下操作系统都试了，都会出现以上问题，而且用工具远程连接会出现，不用工具直接连接服务器也会出现：
CentOS Linux release 7.9.2009 (Core)
Anolis OS release 8.8

### Screenshots（屏幕截图）

![image](https://github.com/user-attachments/assets/6a75390c-b6f4-4ce4-9476-4c47bb2593da)

**Comment by xuthus5** [comment]
新版本已修复该问题，可自行编译构建新版本。
```go
git clone https://github.com/openGemini/openGemini
cd app/ts-cli
go build .
```
