### ISSUE TITLE
application/x-msgpack 返回内容对时间的处理不正确

### ISSUE THREAD

**Issue by stillywud** [openGemini/openGemini#761]
### Describe the bug（Bug 描述）
版本1.3   docker方式部署
docker run --name=opengemini13 --hostname=user-PC --env=tach=true --network=host --privileged --restart=always --runtime=runc --detach=true docker.io/opengeminidb/opengemini-server:latest ts-server

请求如下
http://192.168.28.147:8099/query?db=NOAA_water_database&q=SELECT * FROM weather&chunked=true&chunk_size=20000&format=x-msgpack
不带
Accept application/x-msgpack
![image](https://github.com/user-attachments/assets/d4e4e4d0-7516-48a8-9875-e65e33463361)
返回如下
{"results":[{"statement_id":0,"series":[{"name":"weather","columns":["time","location","temperature"],"values":[["2016-06-13T17:43:50.1004002Z","us-midwest",82]]}]}]}

带上
Accept application/x-msgpack
返回
![image](https://github.com/user-attachments/assets/1145ff7e-a101-4469-a303-41f2fff97764)

hex数据为
81a7726573756c74739182ac73746174656d656e745f696400a67365726965739183a46e616d65a777656174686572a7636f6c756d6e7393a474696d65a86c6f636174696f6eab74656d7065726174757265a676616c7565739193c70c0500000000575ef0d605fbfc48aa75732d6d696477657374cb4054800000000000
这个hex数据用在线转换
https://harmar.site/
发现时间字段不能正确处理
![image](https://github.com/user-attachments/assets/f2c563b8-36dd-4886-a3ca-81bc6d9fc72c)

正确的hex数据期望应该是
用网站https://msgpack.solder.party/#
{"results":[{"statement_id":0,"series":[{"name":"weather","columns":["time","location","temperature"],"values":[["2016-06-13T17:43:50.1004002Z","us-midwest",82]]}]}]}

转换出的
81A7726573756C74739182AC73746174656D656E745F696400A67365726965739183A46E616D65A777656174686572A7636F6C756D6E7393A474696D65A86C6F636174696F6EAB74656D7065726174757265A676616C7565739193BC323031362D30362D31335431373A34333A35302E313030343030325AAA75732D6D69647765737452
![image](https://github.com/user-attachments/assets/3d8d8597-cb1b-42d7-9193-e5c69a75a740)

**Comment by xuthus5** [comment]
Can you give me your test suite? I can't reproduce the issue locally.

**Comment by stillywud** [comment]
> Can you give me your test suite? I can't reproduce the issue locally.

任何数据都行吧，就header请求中加上Accept application/x-msgpack，然后的内容用hex格式，把这个hex格式用https://harmar.site/这个转换成json就发现time字段丢失了。

**Comment by xuthus5** [comment]
我按照你的方法进行复现
```bash
curl --request POST \
  --url 'http://localhost:8086/query?db=NOAA_water_database&chunked=true&chunk_size=20000&format=x-msgpack' \
  --header 'Accept: application/x-msgpack' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'q=select * from weather'
```

得到的结果：
```json
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "weather",
                    "columns": [
                        "time",
                        "location",
                        "temperature"
                    ],
                    "values": [
                        [
                            1465839830100400400,
                            "us-midwest",
                            83
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by stillywud** [comment]
> 我按照你的方法进行复现
> 
> ```shell
> curl --request POST \
>   --url 'http://localhost:8086/query?db=NOAA_water_database&chunked=true&chunk_size=20000&format=x-msgpack' \
>   --header 'Accept: application/x-msgpack' \
>   --header 'content-type: application/x-www-form-urlencoded' \
>   --data 'q=select * from weather'
> ```
> 
> 得到的结果：
> 
> ```json
> {
>     "results": [
>         {
>             "statement_id": 0,
>             "series": [
>                 {
>                     "name": "weather",
>                     "columns": [
>                         "time",
>                         "location",
>                         "temperature"
>                     ],
>                     "values": [
>                         [
>                             1465839830100400400,
>                             "us-midwest",
>                             83
>                         ]
>                     ]
>                 }
>             ]
>         }
>     ]
> }
> ```

我自己又试了一次还是同样的结果，可能是因为我用的是docker版本吗？

**Comment by xuthus5** [comment]
> 我自己又试了一次还是同样的结果，可能是因为我用的是docker版本吗？

我是基于当前主干代码运行的ts-server。

**Comment by stillywud** [comment]
那我再看看吧
