### ISSUE TITLE
ts-store遇见异常停止的情况

### ISSUE THREAD

**Issue by Jafeyyu** [openGemini/openGemini#763]
### Describe the bug（Bug 描述）

openGemini集群运行时出现ts-store异常停止，查看store.error.log发现，在ts-store停止之前，其他的store出现过重启的情况，导致此节点连接其他节点失败，然后写入数据出现pt not found的异常 ，再然后出现了read wal file failed的异常和runtime panic: send on closed channel的异常，最终ts-store服务停止。

### To Reproduce（Bug 复现步骤）

抱歉由于是突发ts-store服务停止，所以也不是特别清楚事件触发的原因和具体条件

### Expected behavior（期望结果）

期望即使是出现异常，服务也能够保持运行，不要停止服务，是其他的数据存储和查询操作还能继续

### Logs（完整的错误日志）

[store.error.log](https://github.com/user-attachments/files/17178703/store.error.log)

**Comment by harry97** [comment]
我之前在往大基数表里写入数据的时候，有些数据的索引列为null值，后台就一直提示插入失败报错，然后我也没有管，大概过了一会，数据库就挂了。然后我停止了往大基数表中写入数据，其他表正常写（并保证没有报错），运行了一个星期目前还是正常

**Comment by fx408** [comment]
进程有异常退出么？需要看下标准输出记录的日志，有没有panic信息

**Comment by shoothzj** [comment]
closed by no updates, feel free to reopen this issue if you found mroe information
