### ISSUE TITLE
全量数据查询比带条件查询数据还要快

### ISSUE THREAD

**Issue by t822876884** [openGemini/openGemini#770]
### Describe your question

我在做海量数据查询性能测试，发现带条件查询的耗时普遍大于不带条件（全量查询）的耗时

带条件查询（取中间时刻）
![带条件查询](https://github.com/user-attachments/assets/bb508c42-8c95-4a64-a9d9-7afae1a3c7da)

不带条件查询全表
![全量查询](https://github.com/user-attachments/assets/bdbd6f9a-78b2-497b-aff6-f83d6ea3be15)

对应库的保留策略如下
![数据保留策略](https://github.com/user-attachments/assets/25b21812-bce7-477d-8b59-31e6a327218d)

**Comment by xiangyu5632** [comment]
openGemini对于一些常见的聚合操作都有预计算，在数据写入时就计算好，并保存在文件头元数据中。这当中就包括count。
计算全量的count，只需要把全量文件头中的元数据读出来，相加就可以很快返回。
但是给定时间条件的情况下，可能就要扫描具体文件的数据，读取文件进行计算。是可能存在比全量慢的情况。
