### ISSUE TITLE
Optional compression protocols or transmission protocols for client side (Performance)

### ISSUE THREAD

**Issue by xkx9431** [openGemini/openGemini#775]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

When the client's query result is large, using a Gzip compressor may not be sufficient. We can explore additional options to improve performance.

### Describe the solution you'd like（问题的解决办法是什么）

We can try add  Brotli.

Refers for others
1. **Brotli**: Developed by Google, Brotli often provides better compression ratios than Gzip, especially for web content.
2. **Zstandard (Zstd)**: Developed by Facebook, Zstandard offers high compression ratios with fast compression and decompression speeds.
3. **LZMA (Lempel-Ziv-Markov chain algorithm)**: Often used in 7z format, it provides high compression ratios but may be slower.
4. **LZ4**: Known for its extremely fast compression and decompression speeds, though it generally achieves lower compression ratios compared to others.
5. **Snappy**: Developed by Google, Snappy aims for very high speeds and reasonable compression ratios, and is often used in big data applications.
6. **bzip2**: Provides better compression ratios than Gzip but at the cost of speed.

**Comment by xkx9431** [comment]
I want to take this task also

**Comment by fx408** [comment]
Brotli 需要依赖动态链接库，需要环境上安装 Brotli
尽量选择支持静态编译的算法，比如 Zstd，LZ4，Snappy
此外，可以尽量支持多种算法，实际使用时可以按业务需要进行选择

**Comment by vicky-run** [comment]
https://github.com/openGemini/openGemini/blob/main/lib/util/lifted/influx/httpd/response_writer.go，这里面有个x-msgpack编码方式，后面可以做下x-msgpack的go客户端适配，大数据返回时，查询性能可以提升几倍

**Comment by xkx9431** [comment]
> [https://github.com/openGemini/openGemini/blob/main/lib/util/lifted/influx/httpd/response_writer.go，这里面有个x-msgpack编码方式，后面可以做下x-msgpack的go客户端适配，大数据返回时，查询性能可以提升几倍]

will resolve this in this PR: [ feat: enable config http header for 'x-msgpack'](https://github.com/openGemini/opengemini-client-go/pull/191)

**Comment by xkx-dev** [comment]
@xiangyu5632 @vicky-run , 当前已经扩展了基于msgpack format 和 zstd 压缩算法。
其中具体包含 x-msgpack的go客户端适配， zstd 的 服务端实现和客户端实现。更新了客户端设计文档， 后面也可以基于当前实现继续扩展。 我们可以先resolve 这个issue.

**Comment by xkx9431** [comment]
@xiangyu5632 @vicky-run , 当前已经扩展了基于msgpack format 和 zstd 压缩算法。
其中具体包含 x-msgpack的go客户端适配， zstd 的 服务端实现和客户端实现。更新了客户端设计文档， 后面也可以基于当前实现继续扩展。 我们可以先resolve 这个issue.
