### ISSUE TITLE
opengemini集群状态 数据库副本数3 当leader 节点服务器强制宕机后，数据写入时延太长（10s）

### ISSUE THREAD

**Issue by LIYI-Git** [openGemini/openGemini#776]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

{"level":"error","time":"2024-10-17T10:55:39.664008252+08:00","msg":"","hostname":"172.23.57.87:8086","error":"read tcp 172.23.57.87:34188->172.23.57.231:8092: read: no route to host","remote_addr":"172.23.57.231:8092","local_addr":"172.23.57.87:34188","SPDY":"MultiplexedConnection","location":"spdy/multiplexed_connection.go:226","repeated":2}
{"level":"error","time":"2024-10-17T10:55:39.66401266+08:00","msg":"","hostname":"172.23.57.87:8086","error":"write tcp 172.23.57.87:34196->172.23.57.231:8092: write: broken pipe","SPDY":"HandleError","location":"spdy/errors.go:113","repeated":2}
{"level":"warn","time":"2024-10-17T10:55:42.614635365+08:00","msg":"read tcp 172.23.57.87:34188->172.23.57.231:8092: read: no route to host","hostname":"172.23.57.87:8086","SPDY":"MultiplexedSessionPool","location":"spdy/multiplexed_session_pool.go:84","repeated":2}
{"level":"error","time":"2024-10-17T10:55:47.50426726+08:00","msg":"[coordinator] retry write rows","hostname":"172.23.57.87:8086","db":"db3","pt":2,"error":"select timeout in 10s seconds","errno":"10611012","location":"coordinator/points_writer.go:797","repeated":1}
{"level":"error","time":"2024-10-17T10:55:47.504332619+08:00","msg":"[coordinator] write rows timeout","hostname":"172.23.57.87:8086","db":"db3","ptIds":[2],"error":"select timeout in 10s seconds","errno":"10611012","location":"coordinator/points_writer.go:782","repeated":1}
{"level":"error","time":"2024-10-17T10:55:47.504415489+08:00","msg":"write point rows timeout","hostname":"172.23.57.87:8086","db":"db3","rp":"","error":"select timeout in 10s seconds","errno":"10611012","location":"coordinator/points_writer.go:247","repeated":1}
{"level":"error","time":"2024-10-17T10:55:47.504459794+08:00","msg":"write error:WritePointsWithContext","hostname":"172.23.57.87:8086","error":"select timeout in 10s seconds","db":"db3","errno":"10611012","location":"httpd/handler.go:1453","repeated":1}

**Comment by lihanxue** [comment]
是否存在重启剩下两个节点的情况呢？

**Comment by xiangyu5632** [comment]
> > 是否存在重启剩下两个节点的情况呢？
> 
> 剩下两个节点查看状态正常，且leader已经切换到正常的节点上

剩下的2个节点有重启过吗？

**Comment by LIYI-Git** [comment]
> > > 是否存在重启剩下两个节点的情况呢？
> > 
> > 
> > 剩下两个节点查看状态正常，且leader已经切换到正常的节点上
> 
> 剩下的2个节点有重启过吗？
 重启过，但是断电的时候集群状态时正常的
