### ISSUE TITLE
查询语句in查出来的数据与预期不符

### ISSUE THREAD

**Issue by fanzhongyu** [openGemini/openGemini#809]
### Describe the bug（Bug 描述）

同时用tag和field in 查，查出来的结果是不带tag过滤条件的

### To Reproduce（Bug 复现步骤）

假设我有个tag叫key，field字段叫state
我使用如下查询语句：
SELECT *
FROM "test" 
WHERE key ='123' AND state in （'end', 'start') and time > now() - 72h AND time < now() 
ORDER BY time DESC
发下查出来的数据没有过滤掉 key ='123'

但是我改为如下查询就没问题：
SELECT *
FROM "test" 
WHERE key ='123' AND (state ='end' or  state ='start')  and time > now() - 72h AND time < now() 
ORDER BY time DESC

所以怀疑是in的问题。

### Expected behavior（期望结果）

同时用tag和field in 查，查出来的结果是要使用到tag过滤条件的

**Comment by fanzhongyu** [comment]
版本是V1.2.0

**Comment by fanzhongyu** [comment]
系统版本 CentOS-7

**Comment by xiangyu5632** [comment]
Please @chen19991212  to explain it

**Comment by xiangyu5632** [comment]
you can see #561

**Comment by xiangyu5632** [comment]
Key='123' AND state IN ('end', 'start') 可以看作为 Key='123' AND  state = 'end' OR state = 'star', 此时该语句会按照(Key='123' AND  state = 'end') OR state = 'star' 解析, 这种情况，如果左边没有满足条件的数据，出现的现象就是Key=‘123条件被忽略了。所以，为保证逻辑的正确，建议添加括号
```
Key='123' AND (state IN ('end', 'start') )
```
等价于
```
Key ='123' AND (state ='end' OR state ='start') 
```
--------------------------------------------------------------------------------------------------

In openGemini, The query condition `Key='123' AND state IN ('end', 'start')` can be seen as `Key='123' AND state = 'end' OR state = 'star'`. In this case, the condition will be parsed as `(Key='123' AND state = 'end') OR state = 'star'`. Therefore, to ensure the correctness of the logic, I recommend you:
```
Key='123' AND (state IN ('end', 'start') )
```
Equivalent to
```
Key ='123' AND (state ='end' OR state ='start')
```

**Comment by fanzhongyu** [comment]
OK
