### ISSUE TITLE
Provide a complete API(HTTP protocol) documentation

### ISSUE THREAD

**Issue by ctlove0523** [openGemini/openGemini#811]
### Is your feature request related to a problem? Please describe.（如果该特性或者功能和已知某个问题相关，请描述问题是什么）

no related problem.

### Describe the solution you'd like（问题的解决办法是什么）

Provide complete API documentation in a separate chapter.

### Describe alternatives you've considered（描述您考虑过的替代方案）

add new chapter of api documentation

### Additional context（其他补充内容）

nothing

**Comment by xiangyu5632** [comment]
For copyright reasons， please see  InfluxDB 1.x document
