### ISSUE TITLE
The regular expression with '\' doesn't return result

### ISSUE THREAD

**Issue by zhenyuxie** [openGemini/openGemini#91]
**Describe the bug** 
I met the scene which querying the measurement used regular expression with escape '\'. I can not get expected results. All sql as follow:
```
> create database mydb
> use mydb
Using database mydb
> insert cpu,region=cd,host=192.168.1.2 value=50.98
> select * from cpu
name: cpu
time                host        region value
----                ----        ------ -----
1671868957585245000 192.168.1.2 cd     50.98
> 
> select * from cpu where host=~/192\.168\.1\.2/
> 
> 
```
We can see, the second query sql doesn't return the rows.

**To Reproduce**
As show above.

**Expected behavior**
The query should return the expected results.

**Comment by xiangyu5632** [comment]
thx @zhenyuxie
