### ISSUE TITLE
Use castor in ts-cli occur service not enabled

### ISSUE THREAD

**Issue by HEEE61** [openGemini/openGemini#94]
### Describe the bug（Bug 描述）

I followed the document to install castor. When I use castor in ts-cli, an error has occurred: service not enabled.

```
openGemini CLI 0.1.0 (rev-revision)
Please use `quit`, `exit` or `Ctrl-D` to exit this program.
>>> use db
Elapsed: 270ns
>>> SELECT castor(value, 'BatchDIFFERENTIATEAD', 'detect_base', 'detect') FROM example GROUP BY tId

Elapsed: 2.676033ms
ERR: service not enabled
```

**Comment by xiangyu5632** [comment]
> ERR: service not enabled
This feature needs to be enabled in the configuration file（[openGemini.conf](https://github.com/openGemini/openGemini/blob/main/config/openGemini.conf) for cluster，[openGemini.singlenode.conf](https://github.com/openGemini/openGemini/blob/main/config/openGemini.singlenode.conf) for single node）

`[castor]  
enabled = true`
`# the node IP addr which run pyworker`
`pyworker-addr = ["127.0.0.1:6666"]`
` # default: 30, connection pool to pyworker`
` connect-pool-size = 30`
` # default: 30 second `
` result-wait-timeout = 30` 
` [castor.detect]`
`   algorithm = ['BatchDIFFERENTIATEAD']`
`   config_filename = ['detect_base']`
` [castor.fit_detect]`
`   algorithm = ['DIFFERENTIATEAD']`
`   config_filename = ['detect_base']`
` [castor.predict]`
`   algorithm = ['METROPD']`
`   config_filename = ['predict_base']`
` [castor.fit]`
`   algorithm = ['METROPD']`
`   config_filename = ['fit_base']`
